-- M7.2a: business transitions append generic, recipient-scoped notification
-- intents in the same transaction, and pg_cron drives the existing activation
-- worker on one named cadence.

begin;
select plan(58);

insert into auth.users (id) values
  ('11111111-1111-1111-1111-111111111111'), -- alice, contest author
  ('22222222-2222-2222-2222-222222222222'), -- bob, invitee/participant
  ('33333333-3333-3333-3333-333333333333'), -- carol, unanswered invitee
  ('44444444-4444-4444-4444-444444444444'); -- dave, unrelated

insert into public.profiles (id, handle, display_name) values
  ('11111111-1111-1111-1111-111111111111', 'alice', 'Alice'),
  ('22222222-2222-2222-2222-222222222222', 'bob',   'Bob'),
  ('33333333-3333-3333-3333-333333333333', 'carol', 'Carol'),
  ('44444444-4444-4444-4444-444444444444', 'dave',  'Dave');

insert into public.friendships (user_a, user_b, requested_by, status) values
  (
    '11111111-1111-1111-1111-111111111111',
    '22222222-2222-2222-2222-222222222222',
    '11111111-1111-1111-1111-111111111111',
    'accepted'
  ),
  (
    '11111111-1111-1111-1111-111111111111',
    '33333333-3333-3333-3333-333333333333',
    '11111111-1111-1111-1111-111111111111',
    'accepted'
  );

insert into public.charities (id, name, ein, slug) values
  (
    'c0000001-0000-0000-0000-000000000001',
    'Trail Fund',
    '12-3456789',
    'trail-fund'
  );

-- ---------------------------------------------------------------------------
-- Generic outbox shape
-- ---------------------------------------------------------------------------

select has_type(
  'public',
  'notification_event_type',
  'notification intents use a closed event vocabulary'
);
select set_eq(
  $$ select enum_value.enumlabel::text
     from pg_catalog.pg_enum enum_value
     join pg_catalog.pg_type enum_type
       on enum_type.oid = enum_value.enumtypid
     join pg_catalog.pg_namespace enum_schema
       on enum_schema.oid = enum_type.typnamespace
     where enum_schema.nspname = 'public'
       and enum_type.typname = 'notification_event_type'
       and enum_value.enumlabel::text = any (array[
         'contest_invitation',
         'contest_activated',
         'contest_cancelled',
         'timezone_consent_requested',
         'timezone_consent_resolved',
         'quarantine_review_requested',
         'quarantine_review_resolved'
       ]::text[]) $$,
  array[
    'contest_invitation',
    'contest_activated',
    'contest_cancelled',
    'timezone_consent_requested',
    'timezone_consent_resolved',
    'quarantine_review_requested',
    'quarantine_review_resolved'
  ],
  'the first M7 transitions all have event types'
);
select has_table(
  'public',
  'notification_intents',
  'the durable notification outbox exists'
);
select col_is_pk(
  'public',
  'notification_intents',
  'id',
  'notification intents have a stable ledger id'
);
select is(
  (
    select string_agg(column_name, ',' order by ordinal_position)
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'notification_intents'
  ),
  'id,recipient_user_id,event_type,entity_id,reminder_stage,not_before,created_at',
  'the outbox contains opaque routing facts and no sensitive payload'
);
select is(
  (
    select is_identity
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'notification_intents'
      and column_name = 'id'
  ),
  'YES',
  'the ledger id is generated by Postgres'
);
select ok(
  (
    select relrowsecurity
    from pg_catalog.pg_class
    where oid = 'public.notification_intents'::regclass
  ),
  'row level security is enabled on notification intents'
);
select has_index(
  'public',
  'notification_intents',
  'notification_intents_recipient_created_idx',
  'recipient inbox order has a supporting index'
);
select is(
  (
    select count(*)
    from pg_catalog.pg_constraint
    where conrelid = 'public.notification_intents'::regclass
      and conname = 'notification_intents_semantic_key'
      and contype = 'u'
  ),
  1::bigint,
  'the semantic event key is unique'
);
select is(
  (
    select count(*)
    from pg_catalog.pg_constraint
    where conrelid = 'public.notification_intents'::regclass
      and contype = 'f'
  ),
  0::bigint,
  'notification history does not cascade with a profile'
);
select ok(
  to_regprocedure(
    'app.emit_notification_intent(uuid,public.notification_event_type,uuid,smallint,timestamptz)'
  ) is not null,
  'the trusted idempotent emitter exists'
);

-- ---------------------------------------------------------------------------
-- Least privilege
-- ---------------------------------------------------------------------------

select ok(
  has_table_privilege(
    'authenticated', 'public.notification_intents', 'select'
  )
  and not has_table_privilege(
    'authenticated', 'public.notification_intents', 'insert'
  )
  and not has_table_privilege(
    'authenticated', 'public.notification_intents', 'update'
  )
  and not has_table_privilege(
    'authenticated', 'public.notification_intents', 'delete'
  ),
  'authenticated users have read-only outbox access'
);
select ok(
  has_table_privilege(
    'service_role', 'public.notification_intents', 'select'
  )
  and not has_table_privilege(
    'service_role', 'public.notification_intents', 'insert'
  )
  and not has_table_privilege(
    'service_role', 'public.notification_intents', 'update'
  )
  and not has_table_privilege(
    'service_role', 'public.notification_intents', 'delete'
  ),
  'service_role also consumes the outbox read-only'
);
select ok(
  not has_table_privilege(
    'anon', 'public.notification_intents', 'select'
  ),
  'anonymous callers cannot read notification intents'
);
select ok(
  not has_function_privilege(
    'anon',
    'app.emit_notification_intent(uuid,public.notification_event_type,uuid,smallint,timestamptz)',
    'execute'
  )
  and not has_function_privilege(
    'authenticated',
    'app.emit_notification_intent(uuid,public.notification_event_type,uuid,smallint,timestamptz)',
    'execute'
  )
  and not has_function_privilege(
    'service_role',
    'app.emit_notification_intent(uuid,public.notification_event_type,uuid,smallint,timestamptz)',
    'execute'
  ),
  'only trusted database transitions can call the emitter'
);
select ok(
  not has_sequence_privilege(
    'anon', 'public.notification_intents_id_seq', 'usage'
  )
  and not has_sequence_privilege(
    'authenticated', 'public.notification_intents_id_seq', 'usage'
  )
  and not has_sequence_privilege(
    'service_role', 'public.notification_intents_id_seq', 'usage'
  ),
  'application roles cannot allocate notification ids directly'
);

-- ---------------------------------------------------------------------------
-- Invitation and cancellation transitions
-- ---------------------------------------------------------------------------

set local role authenticated;
select set_config(
  'request.jwt.claims',
  '{"sub":"11111111-1111-1111-1111-111111111111"}',
  true
);

create temporary table t_cancel as
select public.create_contest(
  'Creator Cancellation',
  'steps',
  'cumulative',
  10000,
  2500,
  now() + interval '3 days',
  now() + interval '8 days',
  'UTC',
  'c0000001-0000-0000-0000-000000000001',
  2::smallint
) as id;

create temporary table t_activate as
select public.create_contest(
  'Scheduled Activation',
  'steps',
  'cumulative',
  10000,
  2500,
  now() + interval '1 day',
  now() + interval '8 days',
  'UTC',
  'c0000001-0000-0000-0000-000000000001',
  3::smallint
) as id;

create temporary table t_void as
select public.create_contest(
  'Scheduled Quorum Failure',
  'steps',
  'cumulative',
  10000,
  2500,
  now() + interval '1 day',
  now() + interval '8 days',
  'UTC',
  'c0000001-0000-0000-0000-000000000001',
  2::smallint
) as id;

select lives_ok(
  $$ insert into public.contest_participants (
       contest_id, user_id, invited_by
     ) values (
       (select id from t_cancel),
       '22222222-2222-2222-2222-222222222222',
       '11111111-1111-1111-1111-111111111111'
     ) $$,
  'a successful invitation commits with its outbox intent'
);
select set_config(
  'request.jwt.claims',
  '{"sub":"22222222-2222-2222-2222-222222222222"}',
  true
);
select is(
  (
    select count(*)
    from public.notification_intents
    where event_type = 'contest_invitation'
      and entity_id = (select id from t_cancel)
      and recipient_user_id = '22222222-2222-2222-2222-222222222222'
      and reminder_stage = 0
  ),
  1::bigint,
  'the invitee receives one generic invitation intent'
);
select set_config(
  'request.jwt.claims',
  '{"sub":"11111111-1111-1111-1111-111111111111"}',
  true
);
select throws_ok(
  $$ insert into public.contest_participants (
       contest_id, user_id, invited_by
     ) values (
       (select id from t_cancel),
       '44444444-4444-4444-4444-444444444444',
       '11111111-1111-1111-1111-111111111111'
     ) $$,
  '42501',
  null,
  'a rejected business transition cannot append an intent'
);
reset role;
select is(
  (
    select count(*)
    from public.notification_intents
    where event_type = 'contest_invitation'
      and entity_id = (select id from t_cancel)
      and recipient_user_id = '44444444-4444-4444-4444-444444444444'
  ),
  0::bigint,
  'the failed invitation left no outbox residue'
);

set local role authenticated;
select set_config(
  'request.jwt.claims',
  '{"sub":"11111111-1111-1111-1111-111111111111"}',
  true
);
insert into public.contest_participants (
  contest_id, user_id, invited_by
) values
  (
    (select id from t_activate),
    '22222222-2222-2222-2222-222222222222',
    '11111111-1111-1111-1111-111111111111'
  ),
  (
    (select id from t_activate),
    '33333333-3333-3333-3333-333333333333',
    '11111111-1111-1111-1111-111111111111'
  ),
  (
    (select id from t_void),
    '22222222-2222-2222-2222-222222222222',
    '11111111-1111-1111-1111-111111111111'
  );

select set_config(
  'request.jwt.claims',
  '{"sub":"22222222-2222-2222-2222-222222222222"}',
  true
);
update public.contest_participants
set status = 'accepted',
    timezone = 'UTC',
    charity_id = 'c0000001-0000-0000-0000-000000000001'
where contest_id = (select id from t_activate)
  and user_id = '22222222-2222-2222-2222-222222222222';

select set_config(
  'request.jwt.claims',
  '{"sub":"11111111-1111-1111-1111-111111111111"}',
  true
);
select lives_ok(
  $$ select public.cancel_contest((select id from t_cancel)) $$,
  'creator cancellation commits with cancellation intents'
);
reset role;

select set_eq(
  $$ select recipient_user_id::text
     from public.notification_intents
     where event_type = 'contest_cancelled'
       and entity_id = (select id from t_cancel) $$,
  array[
    '11111111-1111-1111-1111-111111111111',
    '22222222-2222-2222-2222-222222222222'
  ],
  'creator cancellation notifies the author and the lapsed invitee'
);
select is(
  (
    select status::text
    from public.contest_participants
    where contest_id = (select id from t_cancel)
      and user_id = '22222222-2222-2222-2222-222222222222'
  ),
  'lapsed',
  'the unanswered invitation is closed before cancellation emits'
);

set local role authenticated;
select set_config(
  'request.jwt.claims',
  '{"sub":"11111111-1111-1111-1111-111111111111"}',
  true
);
select throws_ok(
  $$ select public.cancel_contest((select id from t_cancel)) $$,
  '23001',
  null,
  'retrying a completed creator cancellation is refused'
);
reset role;
select is(
  (
    select count(*)
    from public.notification_intents
    where event_type = 'contest_cancelled'
      and entity_id = (select id from t_cancel)
  ),
  2::bigint,
  'the refused retry cannot duplicate cancellation intents'
);

-- RLS exposes only the signed-in recipient's rows, independent of which
-- contests they authored or can otherwise see.
set local role authenticated;
select set_config(
  'request.jwt.claims',
  '{"sub":"11111111-1111-1111-1111-111111111111"}',
  true
);
select ok(
  (
    select count(*) > 0
       and bool_and(
         recipient_user_id = '11111111-1111-1111-1111-111111111111'
       )
    from public.notification_intents
  ),
  'alice sees only notification intents addressed to alice'
);
select set_config(
  'request.jwt.claims',
  '{"sub":"22222222-2222-2222-2222-222222222222"}',
  true
);
select ok(
  (
    select count(*) > 0
       and bool_and(
         recipient_user_id = '22222222-2222-2222-2222-222222222222'
       )
    from public.notification_intents
  ),
  'bob sees only notification intents addressed to bob'
);
select set_config(
  'request.jwt.claims',
  '{"sub":"44444444-4444-4444-4444-444444444444"}',
  true
);
select is(
  (select count(*) from public.notification_intents),
  0::bigint,
  'an unrelated recipient cannot enumerate another inbox'
);
reset role;

-- ---------------------------------------------------------------------------
-- Scheduled activation and worker idempotency
-- ---------------------------------------------------------------------------

create temporary table t_sweep as
select *
from app.activate_due_contests(now() + interval '2 days');

select set_eq(
  $$ select outcome::text from t_sweep $$,
  array['active', 'cancelled'],
  'one sweep activates the quorum contest and cancels the one-person contest'
);
select is(
  (
    select status::text
    from public.contests
    where id = (select id from t_activate)
  ),
  'active',
  'the due contest with a quorum becomes active'
);
select set_eq(
  $$ select recipient_user_id::text
     from public.notification_intents
     where event_type = 'contest_activated'
       and entity_id = (select id from t_activate) $$,
  array[
    '11111111-1111-1111-1111-111111111111',
    '22222222-2222-2222-2222-222222222222'
  ],
  'activation notifies exactly the accepted roster'
);
select is(
  (
    select status::text
    from public.contest_participants
    where contest_id = (select id from t_activate)
      and user_id = '33333333-3333-3333-3333-333333333333'
  ),
  'lapsed',
  'an unanswered invitee lapses and receives no activation intent'
);
select is(
  (
    select status::text || ':' || cancellation_reason::text
    from public.contests
    where id = (select id from t_void)
  ),
  'cancelled:insufficient_participants',
  'the scheduled worker records quorum failure as cancellation'
);
select set_eq(
  $$ select recipient_user_id::text
     from public.notification_intents
     where event_type = 'contest_cancelled'
       and entity_id = (select id from t_void) $$,
  array[
    '11111111-1111-1111-1111-111111111111',
    '22222222-2222-2222-2222-222222222222'
  ],
  'quorum cancellation notifies the author and the newly lapsed invitee'
);
select is_empty(
  $$ select *
     from app.activate_due_contests(now() + interval '2 days') $$,
  'retrying the same activation sweep finds no transition left to perform'
);
select is(
  (
    select count(*)
    from public.notification_intents
    where event_type = 'contest_activated'
      and entity_id = (select id from t_activate)
  ),
  2::bigint,
  'the worker retry cannot duplicate activation intents'
);
select is(
  (
    select count(*)
    from public.notification_intents
    where event_type = 'contest_cancelled'
      and entity_id = (select id from t_void)
  ),
  2::bigint,
  'the worker retry cannot duplicate quorum-cancellation intents'
);

-- ---------------------------------------------------------------------------
-- Installed scheduler registry
-- ---------------------------------------------------------------------------

select ok(
  exists (
    select 1
    from pg_catalog.pg_extension
    where extname = 'pg_cron'
  ),
  'pg_cron is installed'
);
select is(
  (
    select count(*)
    from cron.job
    where jobname = 'gametime-activate-due-contests'
  ),
  1::bigint,
  'the activation worker has one named registry entry'
);
select is(
  (
    select schedule
    from cron.job
    where jobname = 'gametime-activate-due-contests'
  ),
  '* * * * *',
  'activation runs once per minute'
);
select is(
  (
    select command
    from cron.job
    where jobname = 'gametime-activate-due-contests'
  ),
  'select app.activate_due_contests();',
  'the named job calls the server-only activation worker'
);
select ok(
  (
    select active
    from cron.job
    where jobname = 'gametime-activate-due-contests'
  ),
  'the activation job is enabled'
);
select is(
  (
    select database
    from cron.job
    where jobname = 'gametime-activate-due-contests'
  ),
  current_database(),
  'the activation job runs in the database that owns the contest state'
);
select is(
  (
    select username
    from cron.job
    where jobname = 'gametime-activate-due-contests'
  ),
  current_user,
  'the activation job runs as the migration owner'
);
select ok(
  not has_schema_privilege('anon', 'cron', 'usage')
  and not has_schema_privilege('authenticated', 'cron', 'usage')
  and not has_schema_privilege('service_role', 'cron', 'usage'),
  'application roles cannot inspect or mutate scheduler metadata'
);

-- ---------------------------------------------------------------------------
-- Semantic idempotency and append-only enforcement
-- ---------------------------------------------------------------------------

select lives_ok(
  $$ select app.emit_notification_intent(
       '44444444-4444-4444-4444-444444444444',
       'contest_invitation',
       'e0000001-0000-0000-0000-000000000001',
       0,
       '2030-01-01 00:00:00+00'
     ) $$,
  'the trusted emitter appends a semantic event'
);
select lives_ok(
  $$ select app.emit_notification_intent(
       '44444444-4444-4444-4444-444444444444',
       'contest_invitation',
       'e0000001-0000-0000-0000-000000000001',
       0,
       '2030-01-02 00:00:00+00'
     ) $$,
  'an identical semantic event retry is accepted'
);
select is(
  (
    select count(*)
    from public.notification_intents
    where recipient_user_id = '44444444-4444-4444-4444-444444444444'
      and event_type = 'contest_invitation'
      and entity_id = 'e0000001-0000-0000-0000-000000000001'
      and reminder_stage = 0
  ),
  1::bigint,
  'the semantic retry remains one durable row'
);
select is(
  (
    select not_before
    from public.notification_intents
    where recipient_user_id = '44444444-4444-4444-4444-444444444444'
      and event_type = 'contest_invitation'
      and entity_id = 'e0000001-0000-0000-0000-000000000001'
      and reminder_stage = 0
  ),
  '2030-01-01 00:00:00+00'::timestamptz,
  'a retry cannot rewrite the original server schedule'
);
select lives_ok(
  $$ select app.emit_notification_intent(
       '44444444-4444-4444-4444-444444444444',
       'contest_invitation',
       'e0000001-0000-0000-0000-000000000001',
       1,
       '2030-01-02 00:00:00+00'
     ) $$,
  'a distinct reminder stage is a distinct semantic event'
);
select is(
  (
    select count(*)
    from public.notification_intents
    where recipient_user_id = '44444444-4444-4444-4444-444444444444'
      and event_type = 'contest_invitation'
      and entity_id = 'e0000001-0000-0000-0000-000000000001'
  ),
  2::bigint,
  'the outbox retains one row per reminder stage'
);
select throws_ok(
  $$ select app.emit_notification_intent(
       '44444444-4444-4444-4444-444444444444',
       'contest_invitation',
       'e0000001-0000-0000-0000-000000000002',
       -1,
       now()
     ) $$,
  '22023',
  null,
  'a negative reminder stage is rejected'
);
select throws_ok(
  $$ update public.notification_intents
     set not_before = not_before + interval '1 hour'
     where entity_id = 'e0000001-0000-0000-0000-000000000001' $$,
  '23001',
  null,
  'notification intents cannot be updated'
);
select throws_ok(
  $$ delete from public.notification_intents
     where entity_id = 'e0000001-0000-0000-0000-000000000001' $$,
  '23001',
  null,
  'notification intents cannot be deleted'
);
select throws_ok(
  $$ truncate table public.notification_intents $$,
  '23001',
  null,
  'notification intents cannot be truncated'
);

-- The outbox deliberately outlives authentication, but an already-issued JWT
-- must stop authorizing its retained inbox as soon as the profile is gone.
set local role authenticated;
select set_config(
  'request.jwt.claims',
  '{"sub":"44444444-4444-4444-4444-444444444444"}',
  true
);
select is(
  (
    select count(*)
    from public.notification_intents
    where entity_id = 'e0000001-0000-0000-0000-000000000001'
  ),
  2::bigint,
  'the live recipient can read both retained reminder stages'
);
reset role;

delete from auth.users
where id = '44444444-4444-4444-4444-444444444444';

select ok(
  not exists (
    select 1
    from public.profiles
    where id = '44444444-4444-4444-4444-444444444444'
  )
  and (
    select count(*) = 2
    from public.notification_intents
    where recipient_user_id = '44444444-4444-4444-4444-444444444444'
      and entity_id = 'e0000001-0000-0000-0000-000000000001'
  ),
  'account deletion removes the profile but retains its notification history'
);

set local role authenticated;
select set_config(
  'request.jwt.claims',
  '{"sub":"44444444-4444-4444-4444-444444444444"}',
  true
);
select is(
  (select count(*) from public.notification_intents),
  0::bigint,
  'a stale JWT cannot read retained intents after profile deletion'
);
reset role;

select * from finish();
rollback;
