begin;
select no_plan();
\ir fixtures/weekly-fixture.inc
select ok(not has_table_privilege('authenticated','app.weekly_agreements','select'),'no direct agreement table reads');
select ok(not has_table_privilege('service_role','app.weekly_revisions','insert'),'service writes need guarded RPC');
select ok(not has_function_privilege('authenticated','public.capture_weekly_fixture_v1(uuid,uuid,uuid,date,text,integer)','execute'),'client cannot assert fixture completeness');
select ok(not has_function_privilege('anon','public.get_weekly_v1(uuid)','execute'),'anon has no weekly access');
select ok(not has_function_privilege('authenticated','app.weekly_create_at_v1(uuid,jsonb,text,boolean,timestamptz)','execute'),'no public injected-clock seam');
select pg_temp.login(1);
select is(public.get_weekly_preferences_v1()->>'entry_paused','false','pause defaults off');
insert into weekly_test_ids values('two',pg_temp.create_friend(pg_temp.req(100),pg_temp.terms(1,2)));
select is(pg_temp.create_friend(pg_temp.req(100),pg_temp.terms(1,2)),(select id from weekly_test_ids where name='two'),'exact creation retry');
select throws_ok($$select pg_temp.create_friend(pg_temp.req(100),pg_temp.terms(1,3))$$,'22023','weekly_request_conflict','changed roster retry conflicts');
select pg_temp.login(2);
select is(jsonb_array_length(public.get_weekly_v1((select id from weekly_test_ids where name='two'))->'roster'),2,'invited actor sees frozen two roster');
select throws_ok($$select public.accept_weekly_v1(pg_temp.req(101),(select id from weekly_test_ids where name='two'),'wrong',true)$$,'22023','weekly_consent_mismatch','wrong consent rejected');
select pg_temp.accept(pg_temp.req(102),(select id from weekly_test_ids where name='two'));
select is(public.get_weekly_v1((select id from weekly_test_ids where name='two'))->>'accepted_count','2','two explicit consents');
select pg_temp.login(3);
select throws_ok($$select public.get_weekly_v1((select id from weekly_test_ids where name='two'))$$,'42501','weekly_unavailable','third actor cannot read');
reset role;
insert into weekly_test_ids values('three',pg_temp.make_friend(3,3)),('four',pg_temp.make_friend(6,4)),('five',pg_temp.make_friend(10,5));
select is((select count(*) from app.weekly_participants where challenge_id=(select id from weekly_test_ids where name='three') and accepted_at is not null),3::bigint,'three total');
select is((select count(*) from app.weekly_participants where challenge_id=(select id from weekly_test_ids where name='four') and accepted_at is not null),4::bigint,'four total');
select is((select count(*) from app.weekly_participants where challenge_id=(select id from weekly_test_ids where name='five') and accepted_at is not null),5::bigint,'five total');
select throws_ok($$select pg_temp.terms(20,1)$$,'22023','weekly_invalid_terms','one is invalid friend roster');
select throws_ok($$select pg_temp.terms(20,6)$$,'22023','weekly_invalid_terms','six is invalid friend roster');
select pg_temp.login(1);
select throws_ok($$select pg_temp.create_friend(pg_temp.req(110),pg_temp.terms(1,2))$$,'23505','weekly_overlap','overlapping friend blocked');
select public.set_weekly_entry_pause_v1(pg_temp.req(111),true);
select throws_ok($$select pg_temp.create_friend(pg_temp.req(112),pg_temp.terms(1,2,'2026-09-14'))$$,'42501','weekly_admission_closed','pause blocks fresh entry');
select public.submit_weekly_support_v1(pg_temp.req(113),(select id from weekly_test_ids where name='two'),'exit_help');
select is(jsonb_array_length(public.get_weekly_v1((select id from weekly_test_ids where name='two'))->'support'),1,'support works while paused');
select public.set_weekly_entry_pause_v1(pg_temp.req(114),false);
insert into weekly_test_ids values('next',pg_temp.create_friend(pg_temp.req(115),pg_temp.terms(1,2,'2026-09-14')));
select pass('nonoverlapping next-week entry while earlier unsettled');
insert into weekly_test_ids values('third',pg_temp.create_friend(pg_temp.req(116),pg_temp.terms(1,2,'2026-09-21')));
select throws_ok($$select pg_temp.create_friend(pg_temp.req(117),pg_temp.terms(1,2,'2026-09-28'))$$,'23505','weekly_pending_limit','three unsettled entries cap includes earlier week');
reset role;
select public.set_weekly_runtime_v1(false,true,true,'{}');
select pg_temp.login(1);
select is(pg_temp.create_friend(pg_temp.req(100),pg_temp.terms(1,2)),(select id from weekly_test_ids where name='two'),'retry recovers gate off');
select pg_temp.login(2);
select is(pg_temp.accept(pg_temp.req(102),(select id from weekly_test_ids where name='two')),(select id from weekly_test_ids where name='two'),'accept retry recovers gate off');
reset role;
select public.set_weekly_runtime_v1(true,true,true,array(select id from public.profiles where id::text like 'ed000000-%'));
-- Explicit source assertions cannot be inferred from empty, zero or client totals.
select pg_temp.capture((select id from weekly_test_ids where name='two'),10000);
select is((select count(*) from app.weekly_revisions where challenge_id=(select id from weekly_test_ids where name='two')),14::bigint,'server fixture persists all fourteen days');
select throws_ok($$select app.weekly_fixture_at_v1(pg_temp.req(120),(select id from weekly_test_ids where name='two'),pg_temp.actor(1),'2026-09-07','complete',0,'2026-09-16T05:00:00.000001Z')$$,'22023','weekly_fixture_unavailable','microsecond after correction cutoff rejected');
select throws_ok($$select app.weekly_fixture_at_v1(pg_temp.req(121),(select id from weekly_test_ids where name='two'),pg_temp.actor(1),'2026-09-07','complete',0,'2026-09-16T05:00:00Z')$$,'22023','weekly_fixture_unavailable','correction cutoff equality rejected consistently with evaluator');
select is(app.weekly_fixture_at_v1(pg_temp.req(121),(select id from weekly_test_ids where name='two'),pg_temp.actor(1),'2026-09-07','complete',0,'2026-09-16T04:59:59.999999Z'),2,'last eligible microsecond downward correction accepted');
select is(app.weekly_fixture_at_v1(pg_temp.req(121),(select id from weekly_test_ids where name='two'),pg_temp.actor(1),'2026-09-07','complete',0,'2026-09-18T05:00:00Z'),2,'fixture exact retry after cutoff');
select throws_ok($$select app.weekly_fixture_at_v1(pg_temp.req(121),(select id from weekly_test_ids where name='two'),pg_temp.actor(1),'2026-09-07','complete',1,'2026-09-18T05:00:00Z')$$,'22023','weekly_fixture_conflict','fixture changed retry conflicts');
select throws_ok($$select app.weekly_fixture_at_v1(pg_temp.req(122),(select id from weekly_test_ids where name='three'),pg_temp.actor(3),'2026-09-07','complete',0,'2026-09-15T05:00:00.000001Z')$$,'22023','weekly_fixture_cutoff','first upload after grace cannot become correction');
select throws_ok($$select app.weekly_fixture_at_v1(pg_temp.req(123),(select id from weekly_test_ids where name='three'),pg_temp.actor(3),'2026-09-07','complete',0,'2026-09-15T05:00:00Z')$$,'22023','weekly_fixture_cutoff','initial upload cutoff equality rejected consistently with evaluator');
select is(app.weekly_fixture_at_v1(pg_temp.req(123),(select id from weekly_test_ids where name='three'),pg_temp.actor(3),'2026-09-07','complete',0,'2026-09-15T04:59:59.999999Z'),1,'initial upload last eligible microsecond accepted');
-- Community is created only by a service and has one immutable common target.
select app.weekly_curate_at_v1(pg_temp.req(200),'2026-09-07','America/Chicago',63000,2,'2026-08-31T10:00:00Z');
select pg_temp.login(20);
select throws_ok($$select public.curate_weekly_cohort_v1(pg_temp.req(201),'2026-09-07','UTC',1000,10)$$,'42501',null,'participant cannot curate cohort');
select pg_temp.accept(pg_temp.req(202),pg_temp.req(200));
select is(public.get_weekly_v1(pg_temp.req(200))->'own'->>'target_steps','63000','common target frozen on entrant');
select is(jsonb_array_length(public.get_weekly_v1(pg_temp.req(200))->'roster'),0,'community exposes no roster');
select pg_temp.login(21);
select pg_temp.accept(pg_temp.req(203),pg_temp.req(200));
select pg_temp.login(22);
select throws_ok($$select pg_temp.accept(pg_temp.req(204),pg_temp.req(200))$$,'23505','weekly_capacity','capacity enforced');
reset role;
select throws_ok($$select app.weekly_curate_at_v1(pg_temp.req(200),'2026-09-07','America/Chicago',64000,2,'2026-08-31T10:00:00Z')$$,'22023','weekly_cohort_conflict','postjoin common target immutable');
select app.weekly_curate_at_v1(pg_temp.req(210),'2026-09-07','America/Chicago',70000,30,'2026-08-31T10:00:00Z');
select pg_temp.login(3);
select throws_ok($$select pg_temp.accept(pg_temp.req(211),pg_temp.req(210))$$,'23505','weekly_overlap','friend/community overlap blocked');
select pg_temp.login(23);
select throws_ok($$select pg_temp.accept(pg_temp.req(212),pg_temp.req(210),'2026-09-07T04:00:00Z')$$,'55000','weekly_join_unavailable','join cutoff equality closed');
-- Consent-revocable bounded categorical research; no arbitrary payload accepted.
select throws_ok($$select public.record_weekly_pilot_event_v1(pg_temp.req(220),null,'rule_preview','exposure')$$,'42501','weekly_pilot_unavailable','measurement default off');
select public.set_weekly_pilot_consent_v1(pg_temp.req(221),true);
select is(public.get_weekly_preferences_v1()->>'pilot_consent','true','explicit research opt in');
select public.record_weekly_pilot_event_v1(pg_temp.req(222),null,'rule_preview','exposure');
select throws_ok($$select public.record_weekly_pilot_event_v1(pg_temp.req(223),null,'daily_step_total_5000','outcome')$$,'42501','weekly_pilot_unavailable','health values cannot masquerade as event');
select public.set_weekly_pilot_consent_v1(pg_temp.req(224),false);
reset role;
select is((select count(*) from app.weekly_pilot_events where actor_id=pg_temp.actor(23)),0::bigint,'revocation erases events');
select ok(not exists(select 1 from app.weekly_requests where actor_id=pg_temp.actor(23) and payload->>'op'='pilot_event'),'revocation erases reconstructible event payloads from retry ledger');
select pg_temp.login(23);
select throws_ok($$select public.record_weekly_pilot_event_v1(pg_temp.req(222),null,'rule_preview','exposure')$$,'55000','weekly_request_retired','erased optional event key is retired without reconstructible hash');
reset role;
select is((select count(*) from app.weekly_pilot_events where actor_id=pg_temp.actor(23)),0::bigint,'event retry does not recreate revoked data');
-- Blocking preserves only own receipt, and never changes old terms/results.
select pg_temp.login(1);
insert into public.blocks(blocker_id,blocked_id) values(pg_temp.actor(1),pg_temp.actor(2));
select is(jsonb_array_length(public.get_weekly_v1((select id from weekly_test_ids where name='two'))->'roster'),0,'blocked friend roster suppressed');
select is(jsonb_array_length(public.get_weekly_v1((select id from weekly_test_ids where name='two'))->'terms'->'participants'),1,'blocked friend terms redact counterpart');
select is(pg_temp.create_friend(pg_temp.req(100),pg_temp.terms(1,2)),(select id from weekly_test_ids where name='two'),'block preserves committed request recovery');
select pg_temp.exit(pg_temp.req(225),(select id from weekly_test_ids where name='two'),'injury');
select is(public.get_weekly_v1((select id from weekly_test_ids where name='two'))->>'status','closed','injury safely closes friend group');
reset role;
-- Session revocation blocks reads and exact retries.
delete from auth.sessions where id=pg_temp.req(2);
select pg_temp.login(2);
select throws_ok($$select public.get_weekly_v1((select id from weekly_test_ids where name='two'))$$,'42501','weekly_session_required','revoked session blocks history');
select throws_ok($$select pg_temp.accept(pg_temp.req(102),(select id from weekly_test_ids where name='two'))$$,'42501','weekly_session_required','revoked session blocks recovery');
reset role;
-- Verify both DST week lengths with exact local Monday boundaries.
select is(extract(epoch from ((pg_temp.terms(1,2,'2026-03-02','2026-02-28T10:00:00Z')->>'endsAt')::timestamptz-(pg_temp.terms(1,2,'2026-03-02','2026-02-28T10:00:00Z')->>'startsAt')::timestamptz))/3600,167::numeric,'spring DST week is 167 hours');
select is(extract(epoch from ((pg_temp.terms(1,2,'2026-10-26','2026-10-25T10:00:00Z')->>'endsAt')::timestamptz-(pg_temp.terms(1,2,'2026-10-26','2026-10-25T10:00:00Z')->>'startsAt')::timestamptz))/3600,169::numeric,'fall DST week is 169 hours');
select throws_ok($$update app.weekly_revisions set document='{}'$$,'23001','weekly_immutable','fixture ledger immutable');
select throws_ok($$update app.weekly_agreements set terms='{}'$$,'23001','weekly_immutable','agreement immutable');
select throws_ok($$truncate app.weekly_allocations$$,'23001','weekly_immutable','no truncate even owner write guard enabled');
-- Deletion erases optional event payloads as well as primary event rows.
select pg_temp.login(3);
select public.set_weekly_pilot_consent_v1(pg_temp.req(801),true);
select public.record_weekly_pilot_event_v1(pg_temp.req(802),(select id from weekly_test_ids where name='three'),'rule_preview','exposure');
reset role;
select public.delete_account(pg_temp.actor(3));
select is((select payload from app.weekly_requests where actor_id=pg_temp.actor(3) and request_id=pg_temp.req(802)),'{"op":"pilot_erased"}'::jsonb,'deletion keeps only constant optional-event retirement marker');
select is((select count(*) from app.weekly_pilot_events where actor_id=pg_temp.actor(3)),0::bigint,'deletion erases optional measurement rows');

select is((select status from app.weekly_agreements where id=(select id from weekly_test_ids where name='three')),'closed','account deletion safe group closure');
select is((select count(*) from app.weekly_participants where challenge_id=(select id from weekly_test_ids where name='three')),3::bigint,'deletion preserves pseudonymous receipt roster');
select pg_temp.login(4);
select is(jsonb_array_length(public.get_weekly_v1((select id from weekly_test_ids where name='three'))->'roster'),0,'deleted contact hidden at read');
reset role;
select ok((select terms->'policy'=app.weekly_policy_v1() from app.weekly_agreements where id=(select id from weekly_test_ids where name='five')),'W1A policy exactly frozen');
select is((select terms->'lifecycle'->>'filingWindowHours' from app.weekly_agreements where id=(select id from weekly_test_ids where name='five')),'48','full 48h notice filing window frozen');
select is((select terms->'lifecycle'->>'resolutionWindowHours' from app.weekly_agreements where id=(select id from weekly_test_ids where name='five')),'72','full 72h independent resolution window frozen');
select is((select terms->'policy'->>'source' from app.weekly_agreements where id=(select id from weekly_test_ids where name='five')),'fixture_weekly_steps_v1','source explicitly fictional');
select ok(not exists(select 1 from app.weekly_allocations where redeemable),'no redeemable allocation');
select pg_temp.login(35);
select is(public.resolve_weekly_request_v1(pg_temp.req(900))->>'state','cancelled','absent uncertain request safely retired');
select throws_ok($$select pg_temp.create_friend(pg_temp.req(900),pg_temp.terms(35,2))$$,'55000','weekly_request_retired','delayed original request cannot commit after retirement');
select throws_ok($$select public.create_weekly_friend_v1(pg_temp.req(901),jsonb_build_object('participants',jsonb_build_array('{}','{}','{}','{}','{}','{}')),'wrong',true)$$,'22023','weekly_invalid_terms','oversized create rejected before actor locks');
select pg_temp.login(1);
select is(public.resolve_weekly_request_v1(pg_temp.req(100))->>'state','committed','committed uncertain create resolves to retained receipt');
reset role;
select * from finish();
rollback;
