begin;
select no_plan();
\ir fixtures/challenge-fixture.inc
select ok(not has_table_privilege('authenticated','app.challenge_lobbies_v1','select'),'private lobbies');
select ok(not has_function_privilege('authenticated','public.challenge_capture_fixture_v1(uuid,uuid,uuid,bigint,text)','execute'),'participants cannot author completeness');
select ok(not has_function_privilege('anon','public.challenge_detail_v1(uuid)','execute'),'anonymous details denied');
select ok(not has_function_privilege('authenticated','app.challenge_tick_v1(uuid,boolean)','execute'),'private worker');
select throws_ok($$update app.challenge_runtime_v1 set steps_source=true$$,'23514',null,'real source cannot be enabled even by fixture operator');
insert into beta_ids values('two',pg_temp.beta_group(1,2)),('six',pg_temp.beta_group(3,6));
select is((select status from app.challenge_lobbies_v1 where id=(select id from beta_ids where name='two')),'scheduled','two consents schedule');
select is((select count(*) from app.challenge_slots_v1 where challenge_id=(select id from beta_ids where name='six')),6::bigint,'six admission slots');
select pg_temp.login_beta(1);
select is(jsonb_array_length(public.challenge_detail_v1((select id from beta_ids where name='two'))->'members'),2,'two participant projection');
select pg_temp.login_beta(9);
select throws_ok($$select public.challenge_detail_v1((select id from beta_ids where name='six'))$$,'42501','challenge_unavailable','stranger denied');
select pg_temp.login_beta(3);
select pg_temp.beta_mutate((select id from beta_ids where name='six'),'reopen');
reset role;
select is((select count(*) from app.challenge_slots_v1 where challenge_id=(select id from beta_ids where name='six')),0::bigint,'reopen releases slots');
select pg_temp.login_beta(4);
select pg_temp.beta_mutate((select id from beta_ids where name='six'),'target','{"target":20000}');
select pg_temp.login_beta(3);
select throws_ok($$select pg_temp.beta_mutate((select id from beta_ids where name='six'),'target','{"target":100,"actor_id":"bf000000-0000-0000-0000-000000000004"}')$$,'22023','challenge_invalid_request','cannot propose another person target');
select pg_temp.beta_mutate((select id from beta_ids where name='six'),'freeze');
select is(public.challenge_detail_v1((select id from beta_ids where name='six'))->>'agreement_version','2','new immutable agreement version');
select ok(not exists(select 1 from jsonb_array_elements(public.challenge_detail_v1((select id from beta_ids where name='six'))->'members') m where (m->>'consented')::boolean),'new version clears all prior consent');
reset role;
select is((select count(*) from app.challenge_consents_v1 where challenge_id=(select id from beta_ids where name='six') and version=1),6::bigint,'old consents retained');
-- Finish both with fresh consent and service facts; corrections can decrease.
do $$ declare i integer; c uuid:=(select id from beta_ids where name='six'); begin
 for i in 3..8 loop perform pg_temp.login_beta(i); perform pg_temp.beta_mutate(c,'consent',jsonb_build_object('consent',true,'digest',public.challenge_detail_v1(c)->'agreement'->>'digest')); end loop;
 perform set_config('role','none',true);
end $$;
select pg_temp.clock_beta('2026-10-10T06:00Z');
select public.challenge_capture_fixture_v1(pg_temp.br(100),(select id from beta_ids where name='two'),pg_temp.ba(1),12000,'complete');
select public.challenge_capture_fixture_v1(pg_temp.br(101),(select id from beta_ids where name='two'),pg_temp.ba(2),12000,'complete');
select pg_temp.clock_beta('2026-10-12T05:00Z');
select is(public.challenge_capture_fixture_v1(pg_temp.br(102),(select id from beta_ids where name='two'),pg_temp.ba(2),100,'complete'),2,'downward correction accepted at exact cutoff');
select pg_temp.clock_beta('2026-10-12T05:00:00.000001Z');
select throws_ok($$select public.challenge_capture_fixture_v1(pg_temp.br(103),(select id from beta_ids where name='two'),pg_temp.ba(2),200,'complete')$$,'22023','challenge_invalid_fact','correction after cutoff rejected');
-- Delayed publication must give 48 actual hours and never void by itself.
select pg_temp.clock_beta('2026-10-20T12:00Z');
select is(public.challenge_process_v1((select id from beta_ids where name='two')),'review','delayed worker publishes review');
select is((select review_by from app.challenge_notices_v1 where challenge_id=(select id from beta_ids where name='two')),'2026-10-22T12:00Z'::timestamptz,'full actual notice window');
select pg_temp.clock_beta('2026-10-22T11:59:59Z');
select pg_temp.login_beta(2);
select pg_temp.beta_mutate((select id from beta_ids where name='two'),'review','{"notice_revision":1,"reason":"wrong_total"}',pg_temp.br(110));
reset role;
select is((select resolve_by from app.challenge_reviews_v1 where id=pg_temp.br(110)),'2026-10-25T11:59:59Z'::timestamptz,'full resolution from filing');
select pg_temp.clock_beta('2026-10-22T12:00Z');
select is(public.challenge_process_v1((select id from beta_ids where name='two')),'review','open review prevents premature final');
select throws_ok($$select public.challenge_resolve_v1(pg_temp.br(110),pg_temp.ba(1),'upheld')$$,'22023','challenge_invalid_resolution','participant cannot resolve');
select public.challenge_resolve_v1(pg_temp.br(110),pg_temp.ba(30),'upheld');
select is(public.challenge_process_v1((select id from beta_ids where name='two')),'final','resolved complete facts finalize');
select is((select result->'participants'->pg_temp.ba(1)::text->>'returned_cents' from app.challenge_finals_v1 where challenge_id=(select id from beta_ids where name='two')),'200','qualifier returns own and confirmed miss');
select is((select count(*) from app.challenge_slots_v1 where challenge_id=(select id from beta_ids where name='two')),0::bigint,'final releases slots');
select throws_ok($$update app.challenge_finals_v1 set result='{}'$$,'23001','challenge_immutable','final immutable');
select is(public.challenge_process_v1((select id from beta_ids where name='two')),'final','repeated worker preserves final');
select public.challenge_process_v1((select id from beta_ids where name='six'));
select pg_temp.clock_beta('2026-10-25T12:00Z');
select is(public.challenge_process_v1((select id from beta_ids where name='six')),'void','all missing never establishes misses');
select is((select result->>'unallocated_cents' from app.challenge_finals_v1 where challenge_id=(select id from beta_ids where name='six')),'0','missing refunds whole group');
-- Exact retry survives gate/time changes; changed payload fails.
select pg_temp.clock_beta('2026-10-01T12:00Z');
select pg_temp.login_beta(10);
select public.challenge_mutate_v1(pg_temp.br(200),'{"op":"create","config":{"start_date":"2026-10-03","days":1,"timezone":"UTC","amount_cents":50000}}');
reset role;
select pg_temp.clock_beta('2026-11-30T12:00Z',false,false);
select pg_temp.login_beta(10);
select lives_ok($$select public.challenge_mutate_v1(pg_temp.br(200),'{"op":"create","config":{"start_date":"2026-10-03","days":1,"timezone":"UTC","amount_cents":50000}}')$$,'exact retry recovers old committed result with admission off');
select throws_ok($$select public.challenge_mutate_v1(pg_temp.br(200),'{"op":"create","config":{"start_date":"2026-10-03","days":1,"timezone":"UTC","amount_cents":100}}')$$,'22023','challenge_request_conflict','changed request rejected');
reset role;
select * from finish();
rollback;
