begin;
select no_plan();
\ir fixtures/challenge-fixture.inc
select ok(not has_table_privilege('authenticated','app.challenge_age_v1','select'),'age records private');
select ok(not has_function_privilege('anon','public.challenge_redeem_link_v1(uuid,text)','execute'),'anonymous link detail denied');
select ok(not has_function_privilege('authenticated','public.challenge_grant_operator_v1(uuid,uuid,text,timestamptz)','execute'),'participants cannot grant operator scopes');
select pg_temp.login_beta(1);
insert into beta_ids values('lobby',pg_temp.beta_create());
create temp table beta_links(value jsonb);grant all on beta_links to authenticated;
insert into beta_links select public.challenge_issue_link_v1(pg_temp.br(20000),(select id from beta_ids where name='lobby'));
select is(length((select value->>'token' from beta_links)),64,'256-bit invitation token');
select is(public.challenge_issue_link_v1(pg_temp.br(20000),(select id from beta_ids where name='lobby')),(select value from beta_links),'issue exact retry');
create function pg_temp.redeem_beta(n integer) returns jsonb language plpgsql as $$ begin
 perform pg_temp.login_beta(n);return public.challenge_redeem_link_v1(pg_temp.br(20000+n),(select value->>'token' from beta_links));
end $$;
select is(pg_temp.redeem_beta(n)->>'status','pending_request','link unique account '||n||' is pending only') from generate_series(2,21) n;
reset role;
select is((select count(*) from app.challenge_redemptions_v1),20::bigint,'20 unique redemptions');
select is((select count(*) from app.challenge_slots_v1),0::bigint,'pending entrants consume no slots');
select is((select count(*) from app.challenge_members_v1 where challenge_id=(select id from beta_ids where name='lobby') and selected),1::bigint,'redemption does not select roster');
-- Pre-existing all-friends fixture is not link-created friendship evidence.
select pg_temp.login_beta(22);
select throws_ok($$select public.challenge_redeem_link_v1(pg_temp.br(20022),(select value->>'token' from beta_links))$$,'42501','challenge_link_unavailable','21st unique redemption rejected');
select pg_temp.login_beta(2);
select is(public.challenge_redeem_link_v1(pg_temp.br(21002),(select value->>'token' from beta_links))->>'beta_access','true','same account idempotent after ceiling');
select pg_temp.login_beta(1);
select public.challenge_revoke_link_v1(pg_temp.br(22001),((select value->>'id' from beta_links))::uuid);
select pg_temp.login_beta(2);
select is(public.challenge_access_status_v1()->>'beta_access','true','revocation preserves granted access');
select pg_temp.login_beta(22);
select throws_ok($$select public.challenge_redeem_link_v1(pg_temp.br(22022),(select value->>'token' from beta_links))$$,'42501','challenge_link_unavailable','revocation stops new redemption');
select pg_temp.login_beta(1);
select public.challenge_report_v1(pg_temp.br(23001),pg_temp.ba(2),'username');
select is(public.challenge_report_v1(pg_temp.br(23001),pg_temp.ba(2),'username')->>'saved','true','report exact retry');
reset role;
select is((select count(*) from app.challenge_reports_v1),1::bigint,'one private report');
-- Community is a disabled unapproved fixture configuration.
select throws_ok($$select public.challenge_publish_community_fixture_v1(pg_temp.br(24000),pg_temp.ba(40),'{"start_date":"2026-10-03","days":1,"timezone":"UTC","amount_cents":100}',100,2,4,false)$$,'42501','challenge_community_configuration_disabled','ordinary community configuration disabled');
insert into beta_ids values('community',public.challenge_publish_community_fixture_v1(pg_temp.br(24001),pg_temp.ba(40),'{"start_date":"2026-10-03","days":1,"timezone":"UTC","amount_cents":100}',100,2,4,true));
select pg_temp.login_beta(2);
select is(jsonb_array_length(public.challenge_community_catalog_v1()),0,'discovery off by default');
reset role;select public.challenge_discovery_fixture_v1(true);
select pg_temp.login_beta(2);
select is(jsonb_array_length(public.challenge_community_catalog_v1()),1,'one fictional cohort discoverable');
select public.challenge_join_community_v1(pg_temp.br(25002),jsonb_build_object('op','join_community','id',(select id from beta_ids where name='community'),'digest',public.challenge_community_catalog_v1()->0->>'digest','consent',true));
select pg_temp.login_beta(3);
select public.challenge_join_community_v1(pg_temp.br(25003),jsonb_build_object('op','join_community','id',(select id from beta_ids where name='community'),'digest',public.challenge_community_catalog_v1()->0->>'digest','consent',true));
select is(jsonb_array_length(public.challenge_detail_v1((select id from beta_ids where name='community'))->'members'),1,'community exposes only own member');
select is(public.challenge_detail_v1((select id from beta_ids where name='community'))->'counts'->>'joined','2','anonymous joined count');
select ok(public.challenge_detail_v1((select id from beta_ids where name='community'))->'creator_id'='null','operator identity hidden');
reset role;select pg_temp.clock_beta('2026-10-03T12:00Z');
select is(public.challenge_process_v1((select id from beta_ids where name='community')),'active','community minimum schedules at start');
select public.challenge_capture_fixture_v1(pg_temp.br(26002),(select id from beta_ids where name='community'),pg_temp.ba(2),100,'complete');
select public.challenge_capture_fixture_v1(pg_temp.br(26003),(select id from beta_ids where name='community'),pg_temp.ba(3),10,'complete');
select pg_temp.clock_beta('2026-10-06T12:00Z');select public.challenge_process_v1((select id from beta_ids where name='community'));
select pg_temp.clock_beta('2026-10-08T12:00Z');select public.challenge_process_v1((select id from beta_ids where name='community'));
select pg_temp.login_beta(2);
select is(public.challenge_detail_v1((select id from beta_ids where name='community'))->'final'->'result'->'own'->>'returned_cents','200','community own conserved simulation');
reset role;
select * from finish();
rollback;
