begin;
select no_plan();
\ir fixtures/challenge-fixture.inc
insert into beta_ids values('review',pg_temp.beta_group(1,3));
select pg_temp.clock_beta('2026-10-10T12:00Z');
select public.challenge_capture_fixture_v1(extensions.gen_random_uuid(),(select id from beta_ids where name='review'),pg_temp.ba(n),case when n=3 then 0 else 20000 end,'complete') from generate_series(1,3) n;
select pg_temp.clock_beta('2026-10-12T12:00Z');select public.challenge_process_v1((select id from beta_ids where name='review'));
select pg_temp.login_beta(3);
select pg_temp.beta_mutate((select id from beta_ids where name='review'),'review','{"notice_revision":1,"reason":"wrong_result"}',pg_temp.br(30001));
select throws_ok($$select public.challenge_operator_cases_v1((select id from beta_ids where name='review'))$$,'42501','challenge_operator_required','participant cannot read operator cases');
reset role;
select throws_ok($$select public.challenge_grant_operator_v1(pg_temp.ba(1),(select id from beta_ids where name='review'),'review','2026-10-15T12:00Z')$$,'22023','challenge_invalid_grant','participant cannot become own reviewer');
select public.challenge_grant_operator_v1(pg_temp.ba(40),(select id from beta_ids where name='review'),'review','2026-10-15T12:00Z');
select pg_temp.login_beta(40);
select is(jsonb_array_length(public.challenge_operator_cases_v1((select id from beta_ids where name='review'))),1,'assigned authenticated independent reviewer can read structured case');
select public.challenge_command_v1(pg_temp.br(30002),jsonb_build_object('op','resolve','id',(select id from beta_ids where name='review'),'review_id',pg_temp.br(30001),'decision','exclude'));
select is(public.challenge_command_v1(pg_temp.br(30002),jsonb_build_object('op','resolve','id',(select id from beta_ids where name='review'),'review_id',pg_temp.br(30001),'decision','exclude'))->>'saved','true','operator exact retry');
reset role;
select pg_temp.clock_beta('2026-10-14T12:00Z');
select is(public.challenge_process_v1((select id from beta_ids where name='review')),'review','changed outcome starts a fresh review window');
select is((select max(revision) from app.challenge_notices_v1 where challenge_id=(select id from beta_ids where name='review')),2,'new result appended without replacing prior notice');
select is((select max(review_by) from app.challenge_notices_v1 where challenge_id=(select id from beta_ids where name='review')),'2026-10-16T12:00Z'::timestamptz,'new notice gives full actual 48 hours');
select pg_temp.clock_beta('2026-10-16T12:00Z');select public.challenge_process_v1((select id from beta_ids where name='review'));
select is((select result->'participants'->pg_temp.ba(3)::text->>'returned_cents' from app.challenge_finals_v1 where challenge_id=(select id from beta_ids where name='review')),'100','review exclusion refunds');
select pg_temp.login_beta(40);
select throws_ok($$select public.challenge_operator_cases_v1((select id from beta_ids where name='review'))$$,'42501','challenge_operator_required','expired scope cannot read cases');
reset role;
select ok((select count(*)>=3 from app.challenge_operator_audit_v1),'grants, reads and actions audited');
select pg_temp.clock_beta('2026-10-01T12:00Z');
insert into beta_ids values('blocked',pg_temp.beta_group(30,2));
select pg_temp.login_beta(30);
select public.challenge_command_v1(pg_temp.br(30003),jsonb_build_object('op','block','subject',pg_temp.ba(31)));
select is(public.challenge_detail_v1((select id from beta_ids where name='blocked'))->>'social_hidden','true','block hides social details immediately');
select is(public.challenge_detail_v1((select id from beta_ids where name='blocked'))->>'status','void','block safely ends two-person participation');
reset role;
select ok(app.is_blocked_either_way(pg_temp.ba(30),pg_temp.ba(31)),'existing account block preserved');
insert into beta_ids values('suspended',pg_temp.beta_group(20,3));
select public.challenge_grant_operator_v1(pg_temp.ba(40),(select id from beta_ids where name='suspended'),'moderate','2026-10-05T12:00Z');
select pg_temp.login_beta(40);
select public.challenge_command_v1(pg_temp.br(30004),jsonb_build_object('op','suspend','id',(select id from beta_ids where name='suspended'),'actor_id',pg_temp.ba(22),'reason','unsafe_behavior'));
select pg_temp.login_beta(22);
select is(public.challenge_access_status_v1()->>'suspended','true','suspension has explicit state');
select is(public.challenge_detail_v1((select id from beta_ids where name='suspended'))->>'social_hidden','true','suspended actor retains only own receipt');
select throws_ok($$select pg_temp.beta_create()$$,'42501','challenge_admission_paused','suspension prevents new admission');
select lives_ok($$select public.challenge_command_v1(pg_temp.br(30005),jsonb_build_object('op','report','subject',pg_temp.ba(20),'reason','username'))$$,'suspended participant still has safe report');
reset role;
select pg_temp.login_beta(10);
select throws_ok($$select public.challenge_mutate_v1(pg_temp.br(30006),'{"op":"create","policy":"personal_steps_goal_v1","config":{"start_date":"2026-10-03","days":1,"timezone":"UTC","amount_cents":100}}')$$,'42501','challenge_operator_required','personal cannot create a social lobby');
-- Stop an interrupted invitation redemption using its normalized, private hash.
select is(public.challenge_stop_command_v1(pg_temp.br(30007),jsonb_build_object('op','redeem_link','token',repeat('a',64)))->>'status','cancelled_request','uncommitted redemption can be fenced');
select is(public.challenge_command_v1(pg_temp.br(30007),jsonb_build_object('op','redeem_link','token',repeat('a',64)))->>'status','cancelled_request','late redemption cannot bypass stop');
select throws_ok($$select public.challenge_command_v1(pg_temp.br(30007),jsonb_build_object('op','redeem_link','token',repeat('b',64)))$$,'22023','challenge_request_conflict','changed link cannot reuse exact request');
reset role;
select ok(not exists(select 1 from app.challenge_requests_v1 where request_id=pg_temp.br(30007) and payload ? 'token'),'raw redemption token not persisted in journal');
select * from finish();rollback;
