begin;
select no_plan();
\ir fixtures/challenge-fixture.inc
select ok(not has_function_privilege('authenticated','public.challenge_capture_community_snapshot_v1(uuid)','execute'),'snapshot capture is service only');
select ok(not has_function_privilege('authenticated','app.challenge_community_counts_v1(uuid)','execute'),'raw helper private');
select ok(not has_table_privilege('authenticated','app.challenge_community_capacity_v1','select'),'capacity reservations private');
insert into beta_ids values('community',public.challenge_publish_community_fixture_v1(pg_temp.br(60001),pg_temp.ba(40),'{"start_date":"2026-10-03","days":1,"timezone":"UTC","amount_cents":100}',100,2,250,true));
select public.challenge_discovery_fixture_v1(true);
create function pg_temp.community() returns uuid language sql as $$select id from beta_ids where name='community'$$;
create function pg_temp.join_community(n integer) returns jsonb language plpgsql as $$begin
 perform pg_temp.login_beta(n);
 return public.challenge_join_community_v1(pg_temp.br(60100+n),jsonb_build_object('op','join_community','id',pg_temp.community(),'digest',public.challenge_community_catalog_v1()->0->>'digest','consent',true));
end $$;
select pg_temp.join_community(n) from generate_series(1,4) n;
select is(public.challenge_detail_v1(pg_temp.community())->'counts'->>'state','threshold','four members suppress exact count');
select is(public.challenge_detail_v1(pg_temp.community())->'counts'->'joined','null'::jsonb,'below-five count null');
select is(public.challenge_community_catalog_v1()->0->'joined_count','null'::jsonb,'catalog also suppresses count');
reset role;
select public.challenge_capture_community_snapshot_v1(pg_temp.community());
select pg_temp.join_community(5);
select is(public.challenge_detail_v1(pg_temp.community())->>'revision','1','join receipt/detail use member revision');
select is(public.challenge_detail_v1(pg_temp.community())->'counts'->>'state','pending','fifth member still waits for delayed snapshot');
reset role;
select pg_temp.clock_beta('2026-10-01T12:15Z');
select public.challenge_capture_community_snapshot_v1(pg_temp.community());
select pg_temp.clock_beta('2026-10-01T12:29:59Z');select pg_temp.login_beta(1);
select is(public.challenge_detail_v1(pg_temp.community())->'counts'->'joined','null'::jsonb,'899 seconds suppresses snapshot');
reset role;select pg_temp.clock_beta('2026-10-01T12:30Z');select pg_temp.login_beta(1);
select is(public.challenge_detail_v1(pg_temp.community())->'counts'->>'joined','5','900 seconds releases snapshot');
select is(public.challenge_community_catalog_v1()->0->'joined_count','5'::jsonb,'catalog uses identical mature snapshot');
reset role;select pg_temp.clock_beta('2026-10-01T12:30:01Z');select pg_temp.login_beta(1);
select is(public.challenge_detail_v1(pg_temp.community())->'counts'->>'joined','5','901 seconds keeps fixed snapshot');
select is(public.challenge_detail_v1(pg_temp.community())->'counts'->>'as_of','2026-10-01T12:15:00+00:00','snapshot time is original server capture');
select pg_temp.join_community(6);
select pg_temp.login_beta(1);
select is(public.challenge_detail_v1(pg_temp.community())->>'revision','1','another join cannot change own revision');
select is(public.challenge_detail_v1(pg_temp.community())->'counts'->>'joined','5','fresh sixth join remains hidden');
select is(public.challenge_list_v1()->0->'counts'->>'joined','5','legacy list uses same delayed count');
select is(public.challenge_section_v1('upcoming')->'rows'->0->'counts'->>'joined','5','section uses same delayed count');
select is(jsonb_array_length(public.challenge_detail_v1(pg_temp.community())->'members'),1,'stranger identities/activity omitted');
select is(public.challenge_detail_v1(pg_temp.community())->'creator_id','null'::jsonb,'publisher identity hidden');
select is(public.challenge_command_v1(pg_temp.br(60101),jsonb_build_object('op','join_community','id',pg_temp.community(),'digest',public.challenge_community_catalog_v1()->0->>'digest','consent',true))->>'revision','1','dispatcher exact join retry hides total');
select pg_temp.login_beta(6);
select public.challenge_mutate_v1(pg_temp.br(60200),jsonb_build_object('op','leave','id',pg_temp.community(),'revision',1));
select pg_temp.login_beta(1);
select is(public.challenge_detail_v1(pg_temp.community())->>'revision','1','another exit cannot change own revision');
select is(public.challenge_detail_v1(pg_temp.community())->'counts'->>'joined','5','five eligible retains mature count');
select pg_temp.login_beta(5);
select public.challenge_mutate_v1(pg_temp.br(60201),jsonb_build_object('op','leave','id',pg_temp.community(),'revision',1));
select pg_temp.login_beta(1);
select is(public.challenge_detail_v1(pg_temp.community())->'counts'->'joined','null'::jsonb,'exit to four suppresses previously released count');
select is(public.challenge_community_catalog_v1()->0->'counts'->'as_of','null'::jsonb,'threshold does not leak snapshot metadata');
reset role;
select is((select reserved from app.challenge_community_capacity_v1 where challenge_id=pg_temp.community()),4,'exits release narrow capacity reservation');
select public.challenge_grant_operator_v1(pg_temp.ba(40),pg_temp.community(),'moderate','2026-10-05T00:00Z');
select pg_temp.login_beta(40);
select throws_ok($$select public.challenge_operator_action_v1(pg_temp.br(60300),jsonb_build_object('op','suspend','id',pg_temp.community(),'actor_id',pg_temp.ba(1),'reason','unsafe_behavior'))$$,'42501','challenge_operator_required','moderator cannot globally suspend');
select public.challenge_operator_action_v1(pg_temp.br(60301),jsonb_build_object('op','remove','id',pg_temp.community(),'actor_id',pg_temp.ba(4),'reason','unsafe_behavior'));
reset role;
select is((select reserved from app.challenge_community_capacity_v1 where challenge_id=pg_temp.community()),3,'removal releases reservation');
select ok(not exists(select 1 from app.challenge_suspensions_v1 where actor_id=pg_temp.ba(4)),'removal is local only');
select pg_temp.login_beta(1);
select public.challenge_report_scoped_v1(pg_temp.br(60400),pg_temp.community(),null,'unsafe_behavior');
select public.challenge_report_v1(pg_temp.br(60401),pg_temp.ba(2),'username');
select pg_temp.login_beta(40);
select is(jsonb_array_length(public.challenge_operator_reports_v1(pg_temp.community())),1,'only explicitly scoped report visible');
select throws_ok($$select public.challenge_support_reports_v1()$$,'42501','challenge_support_required','moderator cannot read global reports');
reset role;
select public.challenge_revoke_operator_v1(pg_temp.ba(40),pg_temp.community(),'moderate');select pg_temp.login_beta(40);
select throws_ok($$select public.challenge_operator_reports_v1(pg_temp.community())$$,'42501','challenge_operator_required','revoked moderator cannot read');
reset role;
select public.challenge_grant_support_v1(pg_temp.ba(39),'2026-10-05T00:00Z');
select public.challenge_grant_support_v1(pg_temp.ba(38),'2026-10-05T00:00Z');
select pg_temp.login_beta(39);
select is(jsonb_array_length(public.challenge_support_reports_v1()),2,'audited global support reads both scopes');
select public.challenge_support_suspend_v1(pg_temp.br(60500),pg_temp.ba(3),'unsafe_behavior');
select pg_temp.login_beta(3);
select is(public.challenge_access_status_v1()->>'suspended','true','global suspension explicit');
select is(jsonb_array_length(public.challenge_community_catalog_v1()),0,'suspended actor cannot discover');
select lives_ok($$select public.challenge_detail_v1(pg_temp.community())$$,'suspended member retains safe own read');
select public.challenge_appeal_v1(pg_temp.br(60501));
select is(public.challenge_appeal_v1(pg_temp.br(60501))->>'saved','true','appeal exact retry');
select is(public.challenge_access_status_v1()->>'appeal_filed','true','actor-only account status records filed appeal');
select is(jsonb_array_length(public.challenge_own_appeals_v1()),1,'actor sees own appeal');
select pg_temp.login_beta(39);
select throws_ok($$select public.challenge_resolve_appeal_v1(pg_temp.br(60502),pg_temp.br(60501),'reinstate')$$,'42501','challenge_independent_support_required','original suspender cannot decide appeal');
select pg_temp.login_beta(38);
select public.challenge_resolve_appeal_v1(pg_temp.br(60502),pg_temp.br(60501),'reinstate');
select pg_temp.login_beta(3);
select is(public.challenge_access_status_v1()->>'suspended','false','independent support reinstates account');
select is(public.challenge_own_appeals_v1()->0->>'decision','reinstate','own appeal decision visible');
reset role;
select public.challenge_revoke_support_v1(pg_temp.ba(38));select pg_temp.login_beta(38);
select throws_ok($$select public.challenge_support_reports_v1()$$,'42501','challenge_support_required','revoked global support cannot read');
-- Admission pause must not disable safe reads/reviews/exits or permitted discovery.
reset role;select pg_temp.clock_beta('2026-10-01T12:31Z',false,false);select pg_temp.login_beta(2);
select lives_ok($$select public.challenge_detail_v1(pg_temp.community())$$,'read remains available during pause');
select public.challenge_mutate_v1(pg_temp.br(60600),jsonb_build_object('op','leave','id',pg_temp.community(),'revision',1));
select is(public.challenge_detail_v1(pg_temp.community())->'members'->0->>'exited','true','exit remains available during pause');
-- Quotas count discovery and failed token guesses, and block repeated mutations.
reset role;select pg_temp.login_beta(10);
select public.challenge_redeem_link_v1(extensions.gen_random_uuid(),repeat('f',64)) from generate_series(1,20);
select is(public.challenge_redeem_link_v1(extensions.gen_random_uuid(),repeat('f',64))->>'message','challenge_rate_limited','21st token guess is limited');
select public.challenge_community_catalog_v1() from generate_series(1,30);
select is(public.challenge_community_catalog_v1()->>'message','challenge_rate_limited','31st discovery call is limited');
reset role;
select is((select used from app.challenge_quotas_v1 where actor_id=pg_temp.ba(10) and bucket='redemption'),20,'failed guesses persist quota');
select is((select used from app.challenge_quotas_v1 where actor_id=pg_temp.ba(10) and bucket='discovery'),30,'denied discovery does not grow storage');
select ok((select count(*)>=10 from app.challenge_operator_audit_v1),'grants reports suspension appeals and revocation audited');
select * from finish();rollback;
