const out=[];const assert=(ok,m)=>{if(!ok)throw Error(m);};const test=async(name,fn)=>{try{await fn();out.push({name,pass:true});}catch(e){out.push({name,pass:false,error:e.message});}};
const click=s=>page.eval('() => {const e=document.querySelector('+JSON.stringify(s)+');if(!e||e.disabled)throw Error("Missing or disabled "+'+JSON.stringify(s)+');e.click();}');
const go=r=>page.eval('() => SignalDemo.go('+JSON.stringify(r)+',true)');
const change=(sel,v)=>page.eval('() => {const e=document.querySelector('+JSON.stringify(sel)+');e.focus();e.value='+JSON.stringify(v)+';e.dispatchEvent(new Event("input",{bubbles:true}));e.dispatchEvent(new Event("change",{bubbles:true}));}');
await test('Three unfinished challenges block a fourth without erasing consent',async()=>{await page.eval(()=>SignalDemo.reset());await go('agreement');await click('[data-action="friend-check"]');await click('[data-check="consent"]');await click('[data-action="agree"]');await go('communityRules');await click('[data-action="community-check"]');await click('[data-check="communityConsent"]');await click('[data-action="join-community"]');assert(await page.eval(()=>!SignalDemo.state.communityJoined&&!!SignalDemo.state.friendAgreement&&document.querySelector('.error').textContent.includes('three unfinished')),'capacity gate');});
await test('Independent exits retain their own receipts',async()=>{await page.eval(()=>SignalDemo.reset());await go('personalDetail');await click('[data-action="exit:personal"]');await click('[data-action="confirm-exit"]');await go('challengeDetail');assert(await page.eval(()=>document.querySelector('#phone-content').textContent.includes('18,420')),'friend affected by personal exit');await click('[data-action="exit:friends"]');await click('[data-action="confirm-exit"]');await go('history');await click('[data-action="view-exit:personal"]');assert(await page.eval(()=>document.querySelector('#phone-content').textContent.includes('Your running goal')),'personal receipt overwritten');});
await test('Unknown score has no zero or contradictory saved self total',async()=>{await page.eval(()=>SignalDemo.reset());await go('challengeDetail');await page.eval(()=>SignalDemo.setScenario('unavailable'));assert(await page.eval(()=>!document.querySelector('#phone-content').textContent.includes('18,420')&&document.querySelector('#phone-content').textContent.includes('Not available')),'contradictory unknown');});
await test('Stale result cannot bypass review freshness by navigation',async()=>{await go('result');await click('[data-action="demo-review"]');await page.eval(()=>SignalDemo.setScenario('offline'));await click('#phone-content [data-go="review"]');assert(await page.eval(()=>document.querySelector('[data-action="save-review"]').disabled&&document.querySelector('[data-field="reviewReason"]').disabled),'stale review enabled');await click('[data-action="refresh"]');assert(await page.eval(()=>!document.querySelector('[data-field="reviewReason"]').disabled),'refresh did not recover');});
await test('Historical cancellation does not rewrite completed result or payment',async()=>{await go('legacySetup');await click('[data-check="legacyConsent"]');await click('[data-action="legacy-start"]');await click('#phone-content [data-go="legacyExit"]');await click('[data-action="legacy-exit-save"]');await click('[data-action="legacy-replay-payment"]');assert(await page.eval(()=>document.querySelector('#phone-content').textContent.includes('Challenge closed')),'replay payment');await go('legacyDetail');assert(await page.eval(()=>document.querySelector('#phone-content').textContent.includes('52,480')&&document.querySelector('#phone-content').textContent.includes('Goal met')),'historical completed result changed');});
await test('Community active alternate and privacy suppression are coherent',async()=>{await page.eval(()=>SignalDemo.reset());await go('communityRules');await click('[data-action="community-check"]');await click('[data-check="communityConsent"]');await click('[data-action="join-community"]');await click('#phone-content [data-go="communityProgress"]');await change('#community-phase','active');assert(await page.eval(()=>document.querySelector('#phone-content').textContent.includes('18,420')&&document.querySelector('#demo-clock').textContent.includes('Sep 26')),'active clock/score');await change('#community-privacy','suppressed');assert(await page.eval(()=>!document.querySelector('#phone-content').textContent.includes('People taking part')),'count suppression');assert(await page.eval(()=>document.activeElement.id==='community-privacy'||document.activeElement.tagName==='H1'),'privacy focus');});
await test('Reset clears local consents, joins, drafts, exits and receipts',async()=>{await page.eval(()=>SignalDemo.reset());assert(await page.eval(()=>{const s=SignalDemo.state;return s.route==='home'&&!s.joined&&!s.communityJoined&&!s.createConsent&&!s.created&&!s.friendAgreement&&!Object.keys(s.exits).length&&s.draft.target==='';}),'reset incomplete');});

await test('A saved creation cannot be replaced by another draft',async()=>{await page.eval(()=>SignalDemo.reset());await go('challenges');await click('[data-action="create-personal"]');await change('[data-field="draft.target"]','12345');await go('createReview');await click('[data-action="create-check"]');await click('[data-check="createConsent"]');await click('[data-action="create-save"]');await go('createType');await click('[data-action="create-kind:friends"]');await go('createReview');await click('[data-action="create-save"]');assert(await page.eval(()=>SignalDemo.state.created.kind==='personal'&&SignalDemo.state.created.target==='12345'&&document.querySelector('.error').textContent.includes('already saved')),'saved creation replaced');});
await test('An open result review occupies an unfinished slot',async()=>{await page.eval(()=>SignalDemo.reset());await go('result');await click('[data-action="demo-review"]');await go('agreement');await click('[data-action="friend-check"]');await click('[data-check="consent"]');await click('[data-action="agree"]');assert(await page.eval(()=>!SignalDemo.state.friendAgreement&&document.querySelector('.error').textContent.includes('three unfinished')),'open review omitted');});
await test('Editing a proposed goal clears both readiness and consent',async()=>{await page.eval(()=>SignalDemo.reset());await go('agreement');await click('[data-action="friend-check"]');await click('[data-check="consent"]');await click('#phone-content [data-go="proposal"]');await change('[data-field="goal"]','54000');await click('#phone-toolbar [data-action="back"]');assert(await page.eval(()=>!SignalDemo.state.friendReady&&!SignalDemo.state.consent&&document.querySelector('[data-action="agree"]').disabled),'readiness retained');});
await test('Active community exit retains the active fixture date',async()=>{await page.eval(()=>SignalDemo.reset());await go('communityRules');await click('[data-action="community-check"]');await click('[data-check="communityConsent"]');await click('[data-action="join-community"]');await click('#phone-content [data-go="communityProgress"]');await change('#community-phase','active');await click('[data-action="exit:community"]');await click('[data-action="confirm-exit"]');assert(await page.eval(()=>SignalDemo.state.exits.community.savedAt.includes('Sep 26')&&document.querySelector('#demo-clock').textContent.includes('Sep 26')),'wrong exit date');});
console.log(JSON.stringify(out,null,2));
