/* Local fictional prototype. No production transport or account integration. */
(() => {
'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initial=()=>({route:'home',scenario:'populated',metric:'steps',day:6,filter:'Active',history:[],invitation:'open',selected:false,proposed:false,goal:'50000',consent:false,friendReady:false,samAgreed:false,joined:false,friendAgreement:null,resultMode:'complete',reviewSaved:false,reviewReason:'',reviewNote:'',exits:{},exitKind:'friends',viewExitKind:'friends',communityJoined:false,communityConsent:false,communityReady:false,communityPhase:'scheduled',communityDisclosure:'delayed',legacyConsent:false,legacyReviewSaved:false,legacyNote:'My step data is wrong or incomplete',legacyLeft:false,legacyStarted:false,legacyPaymentContext:'completed',createConsent:false,createReady:false,createDirect:false,created:null,draft:{kind:'friends',metric:'steps',target:'',distance:'',days:'7',start:'2026-09-23',amount:'20',name:'A week of steps',zone:'America/Los_Angeles'},error:'',feedback:{},disclosures:{}});
let state=initial();
const icons={home:'<path d="m3 10 9-7 9 7v10H4V10M9 20v-7h6v7"/>',challenges:'<path d="M4 5h16v14H4zM8 2v6m8-6v6M4 10h16"/>',you:'<circle cx="12" cy="7" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/>',back:'<path d="m14 6-6 6 6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',plus:'<path d="M12 4v16M4 12h16"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.challenges}</svg>`;
const button=(label,action,cls='primary',attr='')=>`<button type="button" class="${cls}" data-action="${esc(action)}" ${attr}>${esc(label)}</button>`;
const link=(label,route,cls='secondary')=>`<button type="button" class="${cls}" data-go="${route}">${esc(label)}</button>`;
const row=(title,sub,value,route)=>`<button type="button" class="row" data-go="${route}"><span class="row-copy"><span class="row-title">${esc(title)}</span><span class="row-sub">${esc(sub)}</span></span>${value?`<span class="row-value">${esc(value)}</span>`:''}<span class="row-chevron" aria-hidden="true">›</span></button>`;
const facts=arr=>`<dl class="facts">${arr.map(([k,v])=>`<div class="fact"><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`;
const band=(value,unit,kicker)=>`<div class="goal-band"><p class="eyebrow">${esc(kicker)}</p><div class="metric">${esc(value)}<span class="unit">${esc(unit)}</span></div></div>`;
const dates=(start,end,zone)=>`<div class="date-span"><div><small>First day</small><strong>${esc(start)}</strong></div><span class="date-arrow" aria-hidden="true">→</span><div><small>Last day</small><strong>${esc(end)}</strong></div></div><p class="date-zone">${esc(zone)}</p>`;
const notice=text=>`<div class="notice">${text}</div>`;
const disclosure=(title,html)=>`<details class="rules" data-disclosure="${esc(title)}"><summary>${esc(title)}</summary><div class="rule-content">${html}</div></details>`;
const heading=(title,eyebrow='')=>`${eyebrow?`<p class="eyebrow">${eyebrow}</p>`:''}<h1 tabindex="-1">${title}</h1>`;
const section=(title,html)=>`<section class="section"><h2>${title}</h2>${html}</section>`;
const actions=html=>`<div class="actions">${html}</div>`;
const exitNames={friends:'Week in motion',personal:'Your running goal',timed:'Your 5K goal',community:'September community'};
const exitRow=kind=>row(exitNames[kind],state.exits[kind].savedAt.split(',')[0]+' · You left before the result','View','exitReceipt').replace('data-go="exitReceipt"',`data-action="view-exit:${kind}"`);
const pendingResult=()=>state.reviewSaved||state.resultMode==='pending';
const person=(name,sub,value)=>`<div class="person"><span class="avatar" aria-hidden="true">${name==='You'?'AL':'SP'}</span><span class="person-copy"><strong>${esc(name)}</strong><small>${esc(sub)}</small></span><strong>${esc(value)}</strong></div>`;
const routes={home:['Your activity','Home','home'],challenges:['Challenges','Challenges','challenges'],challengeDetail:['Week in motion','Challenges','goal'],personalDetail:['Your running goal','Challenges','goal'],timedDetail:['Your 5K goal','Challenges','goal'],invitation:['An invitation from Sam','Invitations','invitation'],lobby:['Waiting for Sam','Invitations','lobby'],selection:['Choose the roster','Invitations','lobby'],proposal:['Your step goal','Invitations','lobby'],agreement:['The full agreement','Invitations','agreement'],confirmation:['You’re in','Invitations','receipt'],history:['Finished challenges','History & results','challenges'],result:['The activity result','History & results','result'],review:['Ask for a review','History & results','review'],reviewReceipt:['Saved review request','History & results','reviewReceipt'],exit:['Leave safely','History & results','leave'],exitReceipt:['Saved exit record','History & results','exit'],community:['Community','Community','community'],communityRules:['Community agreement','Community','agreement'],communityConfirmation:['Community joined','Community','receipt'],communityProgress:['Private progress','Community','goal'],legacy:['Existing challenges','Existing challenges','existing'],legacyDetail:['September steps','Existing challenges','goal'],legacySetup:['Original setup','Existing challenges','agreement'],legacyReview:['Review an earlier result','Existing challenges','review'],legacyReceipt:['Saved review','Existing challenges','reviewReceipt'],legacyPayment:['Payment test status','Existing challenges','result'],legacyExit:['Historical cancellation','Existing challenges','leave'],legacyExitReceipt:['Cancellation record','Existing challenges','exit'],createType:['Who’s it for?','Staged creation','create'],createActivity:['Activity and goal','Staged creation','create'],createDates:['Dates','Staged creation','create'],createAmount:['Amount','Staged creation','create'],createReview:['Review','Staged creation','agreement'],createSaved:['Saved confirmation','Staged creation','receipt'],createdDetail:['Your saved goal','Staged creation','goal'],createdLobby:['Your new lobby','Staged creation','lobby'],you:['You','You','you'],support:['Support','You','support']};
const journeys=[['home','Home'],['challenges','Challenges'],['invitation','Invitations'],['history','History & results'],['community','Community'],['legacy','Existing challenges'],['createType','Staged creation'],['you','You']];
const scenarioLabels={populated:'Populated',empty:'Empty',loading:'Loading',offline:'Stale / offline',unavailable:'Unavailable activity',expired:'Expired invitation',pending:'Pending action'};
function availableScenarios(route){
 if(route==='home')return ['populated','empty','loading','offline','unavailable','pending'];
 if(route==='invitation')return ['populated','expired','offline','pending'];
 if(route==='challenges'||route==='history'||route==='legacy')return ['populated','empty','loading','offline','pending'];
 if(route==='community')return ['populated','empty','loading','offline'];
 if(route==='communityProgress')return ['populated','unavailable','offline'];
 if(['challengeDetail','personalDetail','timedDetail','result','legacyDetail','legacyPayment','legacyReview','review'].includes(route))return ['populated','loading','offline','unavailable','pending'];
 if(route.startsWith('create')&&!['createdDetail','createdLobby','createSaved'].includes(route))return ['populated','loading','offline','unavailable'];
 return ['populated'];
}
const notes={
 Home:['Personal activity is distinct from challenge scores saved by GameTime. Refresh and activity status already have native counterparts.','Weekly total leads; one compact selector switches Steps, Activity minutes and Running distance. Timed runs stay in details.','The Home selector, daily series and selected-day readout need their own authorized device-summary model. Unknown days must stay null, never zero.'],
 Challenges:['Friend/personal challenges, invitations and attention states have existing local contracts.','Attention comes first, followed by glass filters and open With friends / Just for you rows.','Grouped list queries, route recovery and all alternative states need native integration and acceptance.'],
 Invitations:['Requesting a place, roster selection, individual goal proposals, full terms and consent are separate product steps.','A large goal band and date span keep the invitation scannable. Consent stays solid and unchecked.','The walkthrough switches fictional roles outside the phone. A real creator cannot propose Alex’s goal or consent for Alex.'],
 'History & results':['Saved notices, participant review and safe-exit records exist as separate local contracts.','Activity result, review and recorded simulated return occupy separate sections.','The result default is a completed fixture. Pending action is a separate provisional fixture with a delayed Sep 20 notice. No local action fabricates a final return.'],
 Community:['Private cohort and delayed aggregate disclosure contracts exist; the original reference showed unavailable entry only.','Published, joined and private-progress variants extend the original composition.','All launch values are fictional: 50,000 steps, Sep 23–29, $20. No real cohort is selected. Anonymous counts require ≥5 current members and a snapshot ≥15 minutes old.'],
 'Existing challenges':['Retained seven-day Personal terms and exact sandbox consent stay intact. A confirmed miss has its own seven-day review.','Focused Back navigation replaces the nested shell. Open rows, precise progress and separate payment status align with Signal.','Original setup/cancellation are an Aug 31 historical replay. The pending-result variant has a delayed Sep 20 notice and Sep 27 review deadline.'],
 'Staged creation':['Current native stages/defaults: friends goal, Steps, blank targets, 7 days, start +2 days, $20. Direct Personal skips Type.','The connected reference retains large exact inputs, glass choices, solid facts, disclosures, separate readiness and explicit consent.','Created receipts capture the selected facts. The new-lobby screen stops at a saved open lobby; its illustrated request is advanced from the reviewer controls.'],
 You:['You remains navigation context. Account, privacy and support functions retain their existing native ownership.','A restrained context screen links back to challenges and support.','This showcase does not redesign or execute account, Health, sign-in, deletion or contact operations.']};
function home(){
 const meta={steps:{title:'Steps',unit:'steps',values:[8230,7450,9020,6800,8430,7550,5000],total:'52,480'},minutes:{title:'Activity minutes',unit:'min',values:[20,30,25,0,35,28,null],total:'138'},distance:{title:'Running distance',unit:'km',values:[0,5.2,0,4.8,0,6.4,0],total:'16.4'}}[state.metric];
 let html=heading('Your activity','SEP 14–20, 2026');
 html+=`<div class="segments" aria-label="Activity">${[['steps','Steps'],['minutes','Activity min'],['distance','Running km']].map(([k,v])=>button(v,'metric:'+k,'',`aria-pressed="${state.metric===k}" aria-label="${k==='minutes'?'Activity minutes':k==='distance'?'Running distance':v}"`)).join('')}</div>`;
 if(['empty','loading','unavailable'].includes(state.scenario)){
 const messages={empty:['Your week starts here.','Your activity will appear after an update. You can browse challenges while you wait.'],loading:['Checking your activity…','You can leave this screen and come back.'],unavailable:['Activity isn’t available.','We can’t read this activity right now. Try Refresh; missing activity won’t become zero.']};
 const [a,b]=messages[state.scenario];html+=`<div class="metric">—<span class="unit">${meta.unit}</span></div>`+notice(`<strong>${a}</strong><br>${b}`)+button('Refresh','refresh','secondary');
 }else{
 const val=meta.values[state.day];html+=`<div class="metric">${meta.total}<span class="unit">${meta.unit}</span></div><p class="metric-sub">${state.metric==='minutes'?'Recorded total · Sunday unavailable':'Your weekly total'} · Apple Health</p>`;
 html+=`<div class="chart"><div class="chart-readout"><strong>${val===null?'Not available':val.toLocaleString('en-US')+' '+meta.unit}</strong><span>${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][state.day]} ${14+state.day} Sep</span></div><div class="chart-plot"><div class="bars" aria-hidden="true">${meta.values.map((n,i)=>`<div class="bar-button ${n===null?'unknown':''} ${i===state.day?'selected':''}" style="--bar-height:${n===null?21:Math.max(3,n/Math.max(...meta.values)*101)}px"><span class="bar-shape"></span><span class="bar-day">${['M','T','W','T','F','S','S'][i]}</span></div>`).join('')}</div><input class="chart-input" id="day-selector" type="range" min="0" max="6" step="1" value="${state.day}" aria-label="Select day" aria-valuetext="${['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][state.day]}, September ${14+state.day}, ${val===null?'activity unavailable':val+' '+meta.unit}"></div><p class="chart-key">${state.metric==='minutes'?'Apple Exercise credit, not every minute of movement. Dashed bar: unavailable.':'Select a day to see its recorded activity.'}</p></div>`;
 html+=`<div class="status-line"><span>${state.scenario==='offline'?'Last update · Sep 20, 8:40 PM':'Updated · Sep 21, 9:40 AM'}</span>${button('Refresh','refresh','text-button')}</div>`;
 if(state.scenario==='offline')html+=notice('You’re offline. Your last update is still here. Try Refresh when you reconnect.');
 }
 html+=`<p class="muted">Your activity here may differ from the challenge scores GameTime has saved.</p>`;
 if(state.scenario==='pending')html+=section('Needs your attention',row('Your result is ready to review','Ask for review by Sep 22 · 12:00 PM Pacific','Open','result'));
 html+=section('Invitation',row('A week of steps','Sam Parker · Sep 30–Oct 6',state.joined?'Agreed':state.invitation==='requested'?'Waiting':'View',state.joined?'confirmation':state.invitation==='requested'?'lobby':'invitation'));
 html+=section('Current challenges',(!state.exits.friends?row('Week in motion','With Sam · 50,000-step goal','18,420','challengeDetail'):'')+(!state.exits.personal?row('Your running goal','Just for you · 20 km this week','6.4 km','personalDetail'):'')+(state.exits.friends&&state.exits.personal?'<p class="muted">Your saved exits are in Finished challenges.</p>':''));
 return html;
}
function challenges(){
 let html=heading('Challenges');
 html+=section('Needs your attention',state.reviewSaved?row('Your review request is saved','September steps · settlement paused','Receipt','reviewReceipt'):pendingResult()?row('Check your September result','Review by Sep 22 · 12:00 PM Pacific','Review','result'):row('Sam invited you','Sep 30–Oct 6 · Steps',state.joined?'Agreed':'Review',state.joined?'confirmation':'invitation'));
 html+=`<div class="segments" aria-label="Challenge filter">${['Active','Upcoming','Finished'].map(x=>button(x,'filter:'+x,'',`aria-pressed="${state.filter===x}"`)).join('')}</div>`;
 if(state.scenario==='loading')html+=notice('Loading your challenges…')+button('Show saved challenges','refresh','secondary');
 else if(state.scenario==='empty')html+=section('No '+state.filter.toLowerCase()+' challenges','<p class="muted">Your challenges will appear here. Start one when it suits you.</p>');
 else if(state.filter==='Active')html+=section('With friends',state.exits.friends?'<p class="muted">No active friend challenge. Your saved exit is in Finished.</p>':row('Week in motion','Sep 18–24 · Steps','18,420','challengeDetail'))+section('Just for you',(!state.exits.personal?row('Your running goal','Sep 21–27 · 20 km','6.4 km','personalDetail'):'')+(state.exits.personal?'<p class="muted">No active personal goals. Your saved exits are in Finished.</p>':''));
 else if(state.filter==='Upcoming')html+=section('With friends',row('A week of steps','Sep 30–Oct 6 · Sam Parker',state.joined?'Agreed':'Waiting',state.joined?'confirmation':'lobby'))+section('Just for you',state.created?.kind==='personal'?row('Your saved goal','Starts '+state.created.start,'View','createdDetail'):'<p class="muted">No upcoming personal goals.</p>');
 else html+=historyRows();
 if(state.scenario==='offline')html+=notice('We couldn’t refresh your challenges. Your saved list is still here. Try Refresh.')+button('Refresh','refresh','secondary');
 html+=actions(link('Create a challenge','createType','primary')+button('Create a personal goal','create-personal','secondary'))+section('More ways to take part',row('Community','One shared goal. Your activity stays private.','','community')+row('Existing challenges','Your earlier Personal agreements','','legacy'));
 return html;
}
function detail(type){
 const personal=type!=='friends', timed=type==='timed',unknown=state.scenario==='unavailable'||timed;
 const title=type==='friends'?'Week in motion':timed?'Your 5K goal':'Your running goal';
 let html=heading(title,personal?'JUST FOR YOU':'WITH SAM PARKER');
 if(state.exits[type])return html+notice('You left this challenge. Your saved exit is available below.')+button('View exit record','view-exit:'+type,'primary');
 html+=band(unknown?'—':personal?'6.4':'18,420',timed?'no eligible run saved':personal?'km saved by GameTime':'steps saved by GameTime',timed?'Finish under 30:00':personal?'Your goal · 20 km':'Your goal · 50,000 steps');
 html+=unknown?notice('No eligible activity is saved yet. This is unknown, not a zero or a missed goal. Try Refresh.'):`<p class="muted">${personal?'32% of your goal':'36.8% of your goal'} · last saved Sep 21, 9:35 AM</p>`;
 html+=dates(personal?'Sep 21, 2026':'Sep 18, 2026',personal?'Sep 27, 2026':'Sep 24, 2026','Pacific Time · 7 full days');
 if(state.scenario==='offline')html+=notice('We couldn’t save your latest activity. This score is your last confirmed update. Try Refresh.');
 html+=actions(button('Refresh','refresh','secondary'));
 if(!personal)html+=section('Agreed goals',person('You','50,000-step goal',unknown?'Not available':'18,420')+person('Sam Parker','60,000-step goal','21,200'));
 if(personal)html+=section('Only you see your activity','<p class="muted">Your challenge progress isn’t shared with friends or the community.</p>');
 html+=facts([['Simulated entry','$20'],['Fee','$0'],['Activity source',timed||personal?'Apple Watch outdoor runs':'Apple Watch steps'],['Corrections by',personal?'Sep 30 · midnight Pacific':'Sep 27 · midnight Pacific']]);
 html+=disclosure('Full challenge rules',
 `<p>${timed?'Finish one whole outdoor run from 5.00 to 5.10 km, including both distances, strictly under 30:00. Time includes pauses. Exactly 30:00 does not meet this goal.':personal?'Reach at least 20 km across eligible whole outdoor runs.':'Alex’s goal is 50,000 eligible steps; Sam’s is 60,000. Each person has their own goal.'}</p>`+
 `<p>${personal?'We count outdoor runs recorded by Apple’s Workout app on Apple Watch. Each whole run must fit inside the challenge dates; a run crossing either boundary does not count.':'We count eligible steps recorded by Apple Watch in Apple Health. Entries marked as manual and records from identifiable unsupported apps or devices do not count.'}</p>`+
 `<p>Starts ${personal?'Sep 21':'Sep 18'}, 2026 at midnight; ends ${personal?'Sep 28':'Sep 25'}, 2026 at midnight, Pacific Time (America/Los_Angeles). Initial activity updates through ${personal?'Sep 29':'Sep 26'} at midnight; corrections through ${personal?'Sep 30':'Sep 27'} at midnight.</p>`+
 `<p>Your simulated entry is $20; fee $0. ${personal?'Meet your goal and your entry returns. A confirmed miss leaves it unallocated.':'People who meet their goals get their own entries back and split entries from confirmed misses evenly. Remainders and an all-miss pool stay unallocated.'} Nothing can be paid out or redeemed. No real money moves.</p>`+
 `<p>Missing or incomplete activity never confirms a miss. If we cannot confirm your result, your entry returns. ${personal?'Your personal goal then does not count.':'If fewer than two people have confirmed results, the challenge does not count and everyone’s entry returns.'}</p>`+
 `<p>You can leave before the result is final; your entry returns. ${personal?'Leaving ends your goal.':'A friend challenge continues only if at least two people with confirmed results remain.'} A saved exit is separate from a recorded simulated return.</p>`+
 '<p>We aim to provide the first result within 72 hours after the challenge ends. You have 48 full hours from the actual notice to request review. A request pauses finalization and the simulated return. Reviewers have 72 hours after filing; delays never shorten these windows.</p>'+
 `<p>${personal?'Your activity and result stay private.':'Friends see only the agreed roster, goals, challenge activity and result. Activity outside this challenge stays private. Every person must agree to the same complete rules; changing the roster or terms requires fresh consent from everyone. Incomplete consent at the start cancels the challenge and returns all entries.'} Assigned reviewers see only the challenge facts needed for your review.</p>`+
 '<p>You may have up to three unfinished challenges at once. Friend challenges for the same activity cannot overlap. The one community challenge may overlap a friend steps challenge.</p>');
 html+=actions(button('Leave this challenge','exit:'+type,'secondary'));
 return html;
}
function invitation(){
 if(state.friendAgreement)return heading('Your agreement is saved.')+notice('You’ve already agreed to this challenge. The saved rules stay available below.')+actions(link('View agreement','agreement','primary')+link('View confirmation','confirmation'));
 let html=heading('A week of steps','FROM SAM PARKER');
 html+=band('60,000','Sam’s step goal','GOALS WITH FRIENDS')+dates('Sep 30, 2026','Oct 6, 2026','Pacific Time · 7 full days')+facts([['Simulated amount','$20 each'],['Fee','$0'],['Request closes','Sep 29 · 6:00 PM Pacific']]);
 if(state.scenario==='expired')return html+notice('This invitation has expired. Ask Sam for a new invitation if you still want to take part.')+link('Back to Challenges','challenges','primary');
 if(state.invitation==='declined')return html+notice('Invitation declined. You haven’t joined or agreed to anything.')+link('Back to Challenges','challenges','primary');
 html+='<p>You’ll choose your own goal if Sam selects you. Requesting a place doesn’t join the challenge.</p><p class="muted">Simulated stakes — no real money moves. Nothing can be paid out or redeemed.</p>';
 if(state.scenario==='offline')return html+notice('We can’t check this invitation right now. Refresh before requesting a place.')+button('Refresh','refresh','primary');
 return html+actions(button('Request a place','request')+button('Decline invitation','decline','secondary'));
}
function lobby(){if(state.friendAgreement)return heading('You’ve already agreed.')+link('View saved agreement','agreement','primary');return heading('Waiting for Sam.','REQUEST SAVED')+notice('You’ve requested a place. Sam chooses the roster before everyone reviews the agreement.')+person('You','Place requested','Waiting')+person('Sam Parker','Creator','60,000 steps')+dates('Sep 30, 2026','Oct 6, 2026','Pacific Time · 7 full days')+facts([['Simulated amount','$20 each'],['Agreed by you','No']])+actions(button('Withdraw request','withdraw-request','secondary')+link('Back to Challenges','challenges'));}
function selection(){if(state.friendAgreement)return heading('This roster is agreed.')+notice('Your saved agreement stays unchanged in this demo. Use Reset demo to explore a new roster.')+link('View saved agreement','agreement','primary');return heading('Choose your roster.','SAM’S VIEW')+'<p>A request doesn’t add anyone automatically.</p>'+person('Sam Parker','Creator · 60,000-step goal','Included')+`<label class="choice-check"><input type="checkbox" data-check="selected" ${state.selected?'checked':''}><span><strong>Alex Lee</strong><br><small>Requested a place · goal to follow</small></span></label>`+facts([['People selected',state.selected?'2 of 6':'1 of 6'],['Simulated amount','$20 each']])+actions(button('Confirm selection','select-roster','primary',state.selected?'':'disabled'))+'<p class="muted">Alex chooses their own goal next. Nobody has agreed yet.</p>';}
function proposal(){if(state.friendAgreement)return heading('Your goal is already agreed.')+notice('Your saved goal and rules stay unchanged. Use Reset demo to explore another agreement.')+link('View saved agreement','agreement','primary');return heading('Choose your step goal.','ALEX’S VIEW')+person('Sam Parker','Sam’s own proposed goal','60,000 steps')+`<div class="fields"><label>Your goal<input class="big-input" data-field="goal" inputmode="numeric" aria-label="Your step goal" value="${esc(state.goal)}"><span class="muted">steps total · Sep 30–Oct 6</span></label></div>`+'<p>Choose a goal that works for you. Sam can’t change it for you.</p>'+actions(button('Save my proposal','propose'))+notice('Everyone reviews the complete agreement before the challenge starts.');}
function friendRules(goal=state.goal){return `<p>Alex’s goal is ${Number(goal).toLocaleString('en-US')} steps; Sam’s is 60,000. Each person must reach their own total.</p><p>Eligible steps are recorded by Apple Watch in Apple Health. Manual entries and identifiable unsupported apps or devices don’t count.</p><p>Starts Sep 30, 2026 at midnight; ends Oct 7, 2026 at midnight, Pacific Time (America/Los_Angeles). Initial updates through Oct 8 at midnight. Corrections through Oct 9 at midnight.</p><p>$20 simulated per person; fee $0. People who meet their goals recover their entries and share confirmed misses equally. If everyone misses, entries stay unallocated. Remainders stay unallocated. Nothing can be paid out or redeemed.</p><p>A missing or unclear result never proves a miss. That person’s entry returns. Fewer than two remaining eligible people cancels the challenge and returns all entries.</p><p>You may leave before the result is final; your entry returns. A saved exit does not confirm a recorded return. You have 48 hours from the actual result notice to ask for review. A submitted review pauses finalization. Reviewers have 72 hours from filing; processing delays do not shorten these windows.</p><p>Each friend can see the agreed roster, goals, challenge scores and results. Activity outside this challenge stays private. Assigned reviewers see only the normalized facts needed for a review.</p><p>Any roster, goal or rule change requires everyone to agree again. If consent is incomplete at the start, the challenge cancels and entries return. Up to three unfinished challenges; friend challenges for the same activity cannot overlap.</p>`;}
function agreement(){const saved=state.friendAgreement,goal=saved?saved.goal:state.goal;return heading(saved?'Your saved agreement.':'Review the agreement.','A WEEK OF STEPS')+band(Number(goal).toLocaleString('en-US'),'your step goal','ALEX LEE')+person('Sam Parker','Sam’s agreed goal','60,000 steps')+dates('Sep 30, 2026','Oct 6, 2026','Pacific Time · 7 full days')+facts([['Starts','Sep 30 · midnight'],['Ends','Oct 7 · midnight'],['Corrections by','Oct 9 · midnight'],['Simulated entry','$20 each'],['Fee','$0']])+'<p>We count eligible Apple Watch steps. Each person has a different goal.</p><p>Meet your goal and your entry returns. People who meet their goals share confirmed misses. Missing activity alone never proves a miss.</p><p>You can leave before the result is final. You have 48 hours from the result notice to ask for a review.</p><p class="muted">Simulated stakes — no real money moves. Nothing can be paid out or redeemed.</p>'+disclosure('Full challenge rules',friendRules(goal))+(saved?notice('You agreed on Sep 21, 2026 at 10:00 AM Pacific. These saved rules stay unchanged in this demo.')+actions(link('View confirmation','confirmation','primary')):activityCheck('friend')+`<label class="consent"><input type="checkbox" data-check="consent" ${state.consent?'checked':''}><span>I have read the complete rules and agree</span></label>`+actions(button('Agree to this challenge','agree','primary',state.consent&&state.friendReady?'':'disabled')+link('Change my goal','proposal')));}
function confirmation(){if(!state.friendAgreement)return heading('Agreement not saved.')+notice('Review the complete rules and choose whether to agree.')+link('Review agreement','agreement','primary');return '<div class="receipt-mark" aria-hidden="true">✓</div>'+heading(state.samAgreed?'You’re in.':'Your agreement is saved.','AGREEMENT SAVED')+band(Number(state.friendAgreement.goal).toLocaleString('en-US'),'your step goal','A WEEK OF STEPS')+dates('Sep 30, 2026','Oct 6, 2026','Pacific Time · 7 full days')+facts([['You','Agreed · Sep 21, 10:00 AM'],['Sam Parker',state.samAgreed?'Agreed · Sep 21, 10:01 AM':'Waiting for agreement'],['Simulated entry','$20 each'],['Fee','$0']])+notice((state.samAgreed?'You and Sam have agreed.':'We’re waiting for Sam to agree to these same rules. If agreement is incomplete at the start, the challenge won’t count.')+' No real money moves; nothing can be paid out or redeemed.')+actions(link('View agreement','agreement','primary')+link('Back to Challenges','challenges'));}
function historyRows(){return section('September 2026',row('September steps','Sep 7–13 · With Sam',state.reviewSaved?'Under review':pendingResult()?'Review open':'Goals met','result')+row('September steps · Personal','Sep 1–7 · Existing agreement','Goal met','legacyDetail'))+(Object.keys(state.exits).length?section('Saved exits',Object.keys(state.exits).map(exitRow).join('')):'');}
function history(){return heading('Finished challenges')+(state.scenario==='empty'?notice('No finished challenges yet. Your results will appear here.'):state.scenario==='loading'?notice('Loading saved results…')+button('Show saved results','refresh','secondary'):historyRows())+(state.scenario==='offline'?notice('Your saved history is here. We couldn’t refresh it. Try again when you reconnect.')+button('Refresh','refresh','secondary'):'')+actions(link('Current challenges','challenges'));}
function result(){
 if(state.scenario==='pending')state.resultMode='pending';
 const unknown=state.scenario==='unavailable',pending=pendingResult();
 const val=unknown?'—':pending?'48,600':'52,480';
 let html=heading('September steps','SEP 7–13, 2026 · WITH SAM')+band(val,'your steps saved',unknown?'Result not confirmed':pending?'Goal missed · review open':'Your goal is met');
 html+=section('Activity result',facts([['Your goal','50,000 steps'],['Sam’s result','61,200 / 60,000 steps'],['Result',unknown?'Not confirmed':pending?'Provisional miss':'Both goals met']]));
 if(unknown)html+=notice('We couldn’t confirm your final activity. Missing steps don’t become zero or a confirmed miss. Try Refresh.');
 if(state.scenario==='offline'||state.scenario==='loading')html+=notice('We couldn’t confirm a fresh result. Your saved update stays here. Refresh before asking for a review.');
 html+=section('Review status',state.reviewSaved?row('Your review request is saved','Final result and return are paused','Receipt','reviewReceipt'):pending?notice('Ask us to review this result by Sep 22, 2026 at 12:00 PM Pacific. Your simulated return is paused.')+link('Request a review','review','primary'):unknown?'<p class="muted">No confirmed result yet.</p>':'<p>Review complete · both goals met.</p>');
 html+=section('Simulated return',unknown||pending?'<h3>Return update pending</h3><p class="muted">No simulated return is recorded yet. A result notice isn’t a return receipt.</p>':'<h3>Simulated return recorded: $20</h3>'+facts([['Recorded','Sep 19, 2026 · 10:00 AM Pacific'],['Your entry','$20'],['Fee','$0']])+'<p class="muted">Nothing can be paid out or redeemed. No real money moved.</p>');
 html+=disclosure('Saved result notice',facts([['Notice sent',pending?'Sep 20, 2026 · 12:00 PM Pacific':'Sep 16, 2026 · 10:00 AM Pacific'],['Review deadline',pending?'Sep 22, 2026 · 12:00 PM Pacific':'Sep 18, 2026 · 10:00 AM Pacific'],['Activity window','Sep 7–13, 2026 · Pacific']])+'<p>Late processing never shortens your review window.</p>');
 return html+actions(button('Refresh','refresh','secondary')+link('Finished challenges','history'));
}
function review(){
 const disabled=['offline','loading','unavailable'].includes(state.scenario);
 if(state.reviewSaved)return heading('Your request is saved.')+link('View review receipt','reviewReceipt','primary');
 return heading('Ask us to review it.')+facts([['Challenge','September steps'],['Your saved steps','48,600'],['Your goal','50,000 steps'],['Result notice','Sep 20 · 12:00 PM Pacific'],['Ask by','Sep 22 · 12:00 PM Pacific']])+notice(disabled?'We couldn’t confirm that review is open. Refresh before sending a request.':'Your final result and simulated return stay paused while we review your request.')+`<div class="fields"><label>What should we check?<select data-field="reviewReason" ${disabled?'disabled':''}><option value="">Choose a reason</option>${['Some activity is missing','My activity is wrong','I disagree with the result'].map(x=>`<option ${state.reviewReason===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Add a note (optional)<textarea data-field="reviewNote" ${disabled?'disabled':''}>${esc(state.reviewNote)}</textarea></label></div>`+actions(button('Save review request','save-review','primary',disabled||!state.reviewReason?'disabled':'')+(disabled?button('Refresh','refresh','secondary'):''));
}
function reviewReceipt(){if(!state.reviewSaved)return heading('No saved request yet.')+link('Review the result','result','primary');return '<div class="receipt-mark" aria-hidden="true">✓</div>'+heading('Your review request is saved.')+facts([['Challenge','September steps'],['Reason',state.reviewReason],['Saved','Sep 21, 2026 · 10:00 AM Pacific'],['Notice reviewed','Sep 20 · 12:00 PM Pacific']])+(state.reviewNote?notice(esc(state.reviewNote)):'')+section('Review status','<p>Under review. We’ll update this challenge when the review is complete.</p>')+section('Simulated return','<p>Paused. No final return is recorded yet.</p>')+actions(link('View result','result','primary')+link('Finished challenges','history'));}
function exitScreen(){return heading('Leave this challenge?')+notice('You can stop here. Leaving doesn’t confirm a missed goal.')+facts([['Challenge',exitNames[state.exitKind]],['Simulated entry','$20'],['After leaving','Entry will return']])+'<p>Your exit is saved first. We’ll show the simulated return when it’s recorded. With fewer than two eligible friends, a friend challenge won’t count.</p>'+actions(button('Leave this challenge','confirm-exit')+button('Keep my place','back','secondary'));}
function exitReceipt(){const receipt=state.exits[state.viewExitKind];if(!receipt)return heading('No exit saved.')+link('View challenges','challenges','primary');return '<div class="receipt-mark" aria-hidden="true">✓</div>'+heading('Your exit is saved.')+facts([['Challenge',receipt.name],['Left',receipt.savedAt],['Activity result','Not a confirmed miss'],['Simulated return','Update pending']])+'<p>You don’t need to continue the activity. A saved exit is separate from a recorded simulated return.</p>'+actions(link('Back to Challenges','challenges','primary')+link('View saved history','history'));}
function community(){
 if(state.scenario==='empty')return heading('Community')+'<div class="empty-symbol" aria-hidden="true">◎</div><h2>No community challenge is open.</h2><p class="muted">When one opens, you can review the dates and rules here. You haven’t joined anything.</p>'+actions(link('Back to Challenges','challenges'));
 if(state.scenario==='loading')return heading('Community')+notice('Checking for a published challenge…')+button('Show saved challenge','refresh','secondary');
 let html=heading('September community','ONE GOAL · YOUR OWN PROGRESS')+band('50,000','steps in 7 days','YOUR GOAL')+dates('Sep 23, 2026','Sep 29, 2026','Pacific Time · 7 full days')+facts([['Simulated entry','$20'],['Fee','$0'],['Join by','Sep 22 · 6:00 PM Pacific']]);
 html+='<p>Your steps and result stay private. Everyone works toward the same goal; this isn’t a leaderboard.</p>';
 if(state.scenario==='offline')return html+notice('We can’t confirm whether places are available. Refresh before joining.')+button('Refresh','refresh','primary');
 return html+actions(link(state.communityJoined?'View my progress':'Review rules',state.communityJoined?'communityProgress':'communityRules','primary'));
}
function communityRules(){if(state.exits.community)return heading('You left this community challenge.')+button('View saved exit','view-exit:community','primary');return heading('Your community agreement.')+band('50,000','steps in 7 days','YOUR OWN GOAL')+dates('Sep 23, 2026','Sep 29, 2026','Pacific Time')+facts([['Starts','Sep 23 · midnight'],['Ends','Sep 30 · midnight'],['Corrections by','Oct 2 · midnight'],['Simulated entry','$20'],['Fee','$0']])+'<p>We count eligible Apple Watch steps. Meet your goal and your entry returns. People who meet the goal share confirmed misses. Missing activity never proves a miss.</p><p>Only you see your activity and result. Community counts are anonymous and delayed.</p><p>You can leave before the result is final. Ask for review within 48 hours after the result notice.</p><p class="muted">Nothing can be paid out or redeemed. No real money moves.</p>'+disclosure('Full community rules','<p>Reach 50,000 eligible Apple Watch steps during the seven full Pacific calendar days. Manual entries and identifiable unsupported sources don’t count.</p><p>Initial updates through Oct 1 at midnight; corrections through Oct 2 at midnight. Missing or unclear results never prove a miss; those entries return.</p><p>People who meet the goal recover their entries and split confirmed misses evenly. If everyone misses, the pool stays unallocated. Remainders stay unallocated. Fee $0. All amounts are simulated. This fictional challenge needs at least two people with confirmed results; with fewer than two, the challenge does not count and everyone’s entry returns.</p><p>Everyone may leave before finalization and recover their entry. An assigned reviewer can inspect only the normalized facts needed to review your result. You have 48 hours from the actual notice to request review. Reviewers have 72 hours after filing; delays do not shorten those windows.</p><p>Other members cannot see your name, activity or individual result. Anonymous counts appear only when at least five current members are included in a saved update at least 15 minutes old. Otherwise no count is shown. Five is a privacy threshold, not an outcome minimum.</p><p>Up to three unfinished challenges at once. One community may overlap a friend steps challenge. No automatic enrollment in another round.</p>')+activityCheck('community')+`<label class="consent"><input type="checkbox" data-check="communityConsent" ${state.communityConsent?'checked':''}><span>I have read the complete rules and agree</span></label>`+actions(button('Join this challenge','join-community','primary',state.communityConsent&&state.communityReady?'':'disabled'));}
function communityConfirmation(){if(!state.communityJoined)return heading('You haven’t joined yet.')+link('Review community rules','communityRules','primary');return '<div class="receipt-mark" aria-hidden="true">✓</div>'+heading('Your place is saved.')+band('50,000','your step goal','SEPTEMBER COMMUNITY')+dates('Sep 23, 2026','Sep 29, 2026','Pacific Time · 7 full days')+facts([['Simulated entry','$20'],['Real money','$0'],['Your progress','Private']])+actions(link('View my progress','communityProgress','primary')+link('Back to Challenges','challenges'));}
function communityProgress(){
 if(state.exits.community)return heading('You left this community challenge.')+notice('Your saved exit stays in your history. Your simulated return is pending.')+button('View saved exit','view-exit:community','primary');
 if(!state.communityJoined)return heading('Your progress stays private.')+notice('Review the rules and agree before joining this fictional community.')+link('Review rules','communityRules','primary');
 let html=heading('Your community goal.','ONLY YOU SEE YOUR STEPS')+(state.communityPhase==='active'?band(state.scenario==='unavailable'?'—':'18,420','steps saved by GameTime','50,000-STEP GOAL')+'<p class="muted">'+(state.scenario==='unavailable'?'No confirmed score available.':'36.8% of your goal · saved Sep 26, 9:35 AM')+'</p>':band('—','starts Sep 23','50,000-STEP GOAL')+notice('Your challenge hasn’t started. There’s no challenge score yet.'))+dates('Sep 23, 2026','Sep 29, 2026','Pacific Time · 7 full days');
 html+=section('Community update',state.communityDisclosure==='delayed'?facts([['People taking part','12'],['Updated',(state.communityPhase==='active'?'Sep 26':'Sep 21')+' · 9:40 AM Pacific']])+'<p class="muted">A saved anonymous count, 20 minutes old. Individual activity and results stay private.</p>':'<p>Community numbers aren’t available. Your own progress stays private.</p>');
 if(state.scenario==='unavailable')html+=notice('Activity isn’t available right now. Try Refresh later. This won’t become a zero.');
 if(state.scenario==='offline')html+=notice('Your last saved update is here. Refresh when you reconnect.');
 return html+actions(button('Refresh','refresh','secondary')+button('Leave this challenge','exit:community','secondary'));
}
function createdRoute(){
 if(!state.created)return heading('No challenge saved yet.')+link('Create a challenge','createType','primary');
 const d=state.created;
 if(state.route==='createdDetail')return heading('Your saved goal.')+band(d.target,{steps:'steps total',minutes:'minutes : seconds',distance:'km total',timed:'time to beat'}[d.metric],'JUST FOR YOU')+facts([['Starts',d.start+' · midnight'],['Duration',d.days+' full days'],['Time zone',d.zone],['Simulated amount','$'+d.amount],['Status','Scheduled']])+notice('Your activity will begin counting on the agreed start date. No challenge score is saved yet.')+actions(link('Saved agreement','createSaved','primary')+link('Back to Challenges','challenges'));
 return heading('Your lobby is ready.')+facts([['Activity',{steps:'Steps',minutes:'Activity minutes',distance:'Running distance',timed:'Timed run'}[d.metric]],['Starts',d.start],['Length',d.days+' full days'],['Time zone',d.zone],['Simulated entry','$'+d.amount+' each']])+person('You','Creator','Included')+notice('No one has requested a place yet. You choose the roster before everyone reviews the agreement.')+actions(button(state.linkMade?'Invitation link saved':'Create invitation link','create-link','primary')+link('Saved lobby details','createSaved'))+(state.linkMade?notice('Your invitation link is ready in this demo. It hasn’t been sent to anyone. Link expires Oct 21, 2026; closes after 20 unique requests.'):'' );
}
function you(){return heading('You')+person('Alex Lee','@alexlee','')+section('Your account',row('Existing challenges','Your earlier steps agreements','','legacy')+row('Help and support','Questions about a challenge','','support'))+notice('Account, privacy and activity settings stay in their current app locations. This preview keeps You as navigation context.')+actions(link('Back to Home','home','primary'));}
function support(){return heading('Support')+'<p>Tell us which challenge needs help. In the app, this opens the current support route.</p>'+notice('This local preview doesn’t send a message. Use Back to return to your saved challenge.')+actions(button('Back to my challenge','back','primary'));}
function activityCheck(kind){const ready=state[kind+'Ready'];return section(ready?'Activity found':'Check your activity','<p class="muted">'+(ready?'We found matching activity. This doesn’t mean your entire history is available.':'Check your activity before you agree. This does not agree to the rules for you.')+'</p>'+button('Refresh activity check',kind+'-check','secondary'));}
function admissionCount(){return 2+Number(pendingResult())+Number(!!state.friendAgreement)+Number(state.communityJoined||!!state.exits.community)+Number(state.created?.kind==='personal');}
function capacityBlocked(){if(admissionCount()<3)return false;error('You already have three unfinished challenges. Wait until one finishes before agreeing to another. Your current agreements stay saved.');return true;}
function screen(){
 const ctx={state,esc,button,row,facts,band,dates,notice,disclosure};
 const c=window.renderCreation?.(state.route,ctx);if(c!==null&&c!==undefined)return c;
 const l=window.renderLegacy?.(state.route,ctx);if(l!==null&&l!==undefined)return l;
 const map={home,challenges,challengeDetail:()=>detail('friends'),personalDetail:()=>detail('personal'),timedDetail:()=>detail('timed'),invitation,lobby,selection,proposal,agreement,confirmation,history,result,review,reviewReceipt,exit:exitScreen,exitReceipt,community,communityRules,communityConfirmation,communityProgress,createdDetail:createdRoute,createdLobby:createdRoute,you,support};
 return map[state.route]();
}
function focusKey(el){return el?.id?['id',el.id]:el?.dataset.action?['data-action',el.dataset.action]:el?.dataset.go?['data-go',el.dataset.go]:el?.dataset.check?['data-check',el.dataset.check]:el?.dataset.field?['data-field',el.dataset.field]:null;}
function setNotes(){const group=routes[state.route][1],n=notes[group];$('#screen-notes').innerHTML=n.map((text,i)=>`<section class="note-block"><h3 class="${i===1?'note-tag':''}">${['Existing behavior','Proposed presentation','Later implementation'][i]}</h3><p>${text}</p></section>`).join('');
 const controls=[];
 if(state.route==='confirmation'&&state.friendAgreement&&!state.samAgreed)controls.push(button('Simulate Sam’s agreement','demo-sam-agree','secondary')+'<p>Advance the fictional second participant. Alex’s saved consent remains separate.</p>');
 if(state.route==='invitation'&&state.scenario==='expired')controls.push('<p><strong>Later-time alternate · Sep 30, 2026.</strong> The Sep 29 invitation deadline has passed. Other journeys use the Sep 21 clock.</p>');
 if(state.error&&state.error.includes('three unfinished'))controls.push('<p>This fixture reached the three-challenge limit. Reset demo to walk another admission independently. A safe exit does not instantly finalize its return.</p>');
 if(state.route==='challenges')controls.push(link('Inspect a timed-run alternative','timedDetail','secondary')+'<p>The timed-run screen is an alternate personal-goal fixture; it is not a third active challenge in this list.</p>');
 if(state.route==='timedDetail')controls.push('<p>This alternate personal-goal fixture shows timed running in place of the cumulative running goal. It is not an additional active challenge.</p>');
 if(state.route==='legacyPayment'&&state.legacyPaymentContext==='replay')controls.push('<p><strong>Historical replay · Aug 31, 2026.</strong> This payment status belongs to the separate setup/cancellation replay. It does not change the completed September record.</p>');
 if(state.route==='lobby')controls.push(button('Continue demo as Sam','demo-select','secondary'));
 if(state.route==='selection')controls.push('<p>Role preview: Sam selects Alex. The next screen returns to Alex.</p>');
 if(state.route==='community')controls.push(button('Show unavailable entry','community-unavailable','secondary'));
 if(state.route==='communityProgress')controls.push(`<label>Challenge phase<select id="community-phase"><option value="scheduled" ${state.communityPhase==='scheduled'?'selected':''}>Scheduled · Sep 21</option><option value="active" ${state.communityPhase==='active'?'selected':''}>Active · Sep 26</option></select></label><label>Privacy fixture<select id="community-privacy"><option value="delayed" ${state.communityDisclosure==='delayed'?'selected':''}>12 members · 20-minute-old count</option><option value="suppressed" ${state.communityDisclosure==='suppressed'?'selected':''}>Count suppressed</option></select></label><p>Suppressed covers either fewer than five current members or an update younger than 15 minutes. The phone reveals neither condition.</p>`);
 if(state.route==='result')controls.push(button('Show review-open result','demo-review','secondary'));
 if(state.route==='legacyDetail')controls.push(button('Show review-open result','demo-legacy-review','secondary'));
 if(state.route.startsWith('legacySetup')||state.route.startsWith('legacyExit'))controls.push('<p><strong>Historical replay · Aug 31, 2026.</strong> These actions explore the original setup and cancellation presentation. They do not restart or cancel the completed September record.</p>');
 if(state.route.startsWith('create')&&state.created)controls.push('<p>Your saved creation stays intact. Use Reset demo before saving another creation; draft edits never replace its receipt.</p>');
 if(state.route==='createdLobby')controls.push(link('Walk a populated invitation','invitation','secondary')+'<p>Separate saved fixture: Sam’s Sep 30 invitation. Your created lobby keeps its selected values.</p>');
 if(controls.length)$('#screen-notes').innerHTML+=`<section class="note-block reviewer-actions"><h3>Walk the demo</h3>${controls.join('')}</section>`;
}
function updateComparison(){
 const original=routes[state.route][2];const url=`reference/index.html?screen=${original}&appearance=${document.documentElement.dataset.theme}&material=${document.documentElement.dataset.material}&motion=${document.documentElement.dataset.motion}`;
 if($('#original').getAttribute('src')!==url)$('#original').src=url;
 const captureMap={createType:'native-final-compact-type',createActivity:'native-final-compact-activity',createDates:'native-final-compact-dates',createAmount:'native-final-compact-amount',createReview:'after-review-top',agreement:'after-review-consent',communityRules:'after-review-consent',legacySetup:'after-review-consent',confirmation:'after-saved',createSaved:'after-saved',result:'after-detail',legacyPayment:'after-detail',challengeDetail:'after-detail'};
 const cap=captureMap[state.route]||(state.route.includes('Receipt')?'after-saved':'native-final-compact-activity');$('#capture').src=`captures/${cap}.png`;
 $('#capture').alt=`September 20 native staged creation capture: ${cap.replaceAll('-',' ')}`;
 $('#original-note').textContent=original==='existing'?'Original empty state; proposed populated layout is new.':original==='community'?'Original unavailable state; published variant is new.':'Original '+original+' layout and visual rhythm.';
 $('#capture-note').textContent=cap.includes('consent')?'Solid rules, explicit consent, glass action.':cap.includes('detail')?'Saved values, date span and clear next action.':cap.includes('saved')?'Receipt and confirmation treatment.':'Precise numbers, readable choices and glass controls.';
 $('#proposal-title').textContent='Proposed '+routes[state.route][0];
}
function render(navigation=false,restore=null){
 const content=$('#phone-content'),oldScroll=content.scrollTop,active=focusKey(document.activeElement);const headingText=routes[state.route][0];
 if(!availableScenarios(state.route).includes(state.scenario))state.scenario='populated';
 $('#screen-label').textContent=headingText;$('#journey-label').textContent=String(journeys.findIndex(x=>x[1]===routes[state.route][1])+1).padStart(2,'0')+' / '+routes[state.route][1].toUpperCase();
 $('#screen-picker').value=state.route;$('#compare-screen').value=state.route;$('#demo-clock').textContent='Demo clock · '+(state.route==='invitation'&&state.scenario==='expired'?'Sep 30':(state.route==='communityProgress'||state.route==='exit'&&state.exitKind==='community'||state.route==='exitReceipt'&&state.viewExitKind==='community')&&state.communityPhase==='active'?'Sep 26':'Sep 21')+', 2026 · '+(state.route==='confirmation'&&state.samAgreed?'10:01':'10:00')+' AM Pacific';$('#scenario').innerHTML=availableScenarios(state.route).map(x=>`<option value="${x}" ${x===state.scenario?'selected':''}>${scenarioLabels[x]}</option>`).join('');
 $('#journey-nav').innerHTML=journeys.map(([r,title],i)=>`<button class="journey-button" data-go="${r}" aria-current="${routes[state.route][1]===title}"><span class="num">0${i+1}</span><span>${title}</span><span class="arrow" aria-hidden="true">↗</span></button>`).join('');
 const root=['home','challenges','you'].includes(state.route);
 $('#phone-toolbar').innerHTML=`<div class="phone-toolbar">${root?`<span class="toolbar-title" style="text-align:left;padding-left:7px">GameTime</span>`:button('Back','back','glass',`aria-label="Back"`)+`<span class="toolbar-title">${esc(routes[state.route][1])}</span>`}${root?`<button class="glass icon-button" data-go="createType" aria-label="Create a challenge">${icon('plus')}</button>`:`<button class="glass icon-button" data-action="close" aria-label="Close">${icon('close')}</button>`}</div>`;
 $('#demo-strip').textContent=state.route.startsWith('legacy')?'Payment test mode — no real money moves.':'Simulated stakes — no real money moves.';
 content.innerHTML=screen()+(state.error?`<p class="error" role="alert">${esc(state.error)}</p>${state.error.includes('already saved')?link('Open saved confirmation','createSaved','secondary'):''}`:'');
 content.querySelectorAll('h1').forEach(x=>x.tabIndex=-1);
 // One ambient historical disclosure; preserve exact decision-point copy.
 if(state.route.startsWith('legacy'))content.querySelectorAll('.notice').forEach(x=>{if(x.textContent==='Payment test mode — no real money moves.')x.remove();});
 content.querySelectorAll('[data-disclosure]').forEach(x=>{x.open=!!state.disclosures[state.route+':'+x.dataset.disclosure];x.addEventListener('toggle',()=>{state.disclosures[state.route+':'+x.dataset.disclosure]=x.open;});});
 const tab=state.route==='home'?'home':['you','support'].includes(state.route)?'you':'challenges';
 $('#tabbar').innerHTML=[['home','Home'],['challenges','Challenges'],['you','You']].map(([r,t])=>`<button data-go="${r}" ${tab===r?'aria-current="page"':''}>${icon(r)}<span>${t}</span></button>`).join('');
 $('#tabbar').hidden=!root&&!['history','community','legacy'].includes(state.route);if($('#tabbar').hidden)$('#tabbar').style.display='none';else $('#tabbar').style.display='flex';
 setNotes();updateComparison();
 $('#feedback-title').textContent=headingText;$('#feedback-note').value=state.feedback[state.route]||'';$('#feedback-status').textContent='Queue here, then Send to Agent in Lavish. Nothing queues while you browse.';
 if(navigation){content.scrollTop=restore?.scroll||0;if(restore?.focus){const [k,v]=restore.focus;const origin=document.querySelector(`[${k}="${CSS.escape(v)}"]`);(origin||content.querySelector('h1'))?.focus({preventScroll:true});}else content.querySelector('h1')?.focus({preventScroll:true});}
 else{content.scrollTop=oldScroll;if(active){const [k,v]=active;document.querySelector(`[${k}="${CSS.escape(v)}"]`)?.focus({preventScroll:true});}}
 try{window.history.replaceState(null,'','#'+state.route);}catch{}document.title='GameTime · Signal · '+headingText;
}
function go(route,fromNav=false){if(!routes[route])return;if(route===state.route)return;const previousRoute=state.route;if(route==='legacyPayment')state.legacyPaymentContext=!fromNav&&previousRoute==='legacyExitReceipt'?'replay':'completed';state.history.push({route:state.route,scenario:state.scenario,legacyPaymentContext:state.legacyPaymentContext,scroll:$('#phone-content').scrollTop,focus:focusKey(document.activeElement)});state.route=route;state.error='';if(fromNav||!availableScenarios(route).includes(state.scenario))state.scenario='populated';if(route==='review'){if(!['offline','loading','unavailable'].includes(state.scenario))state.scenario='pending';state.resultMode='pending';}if(route==='result'&&pendingResult()&&state.scenario==='populated')state.scenario='pending';if(route==='legacyReview'&&!['offline','loading','unavailable'].includes(state.scenario))state.scenario='pending';render(true);}
function back(){const prior=state.history.pop();state.error='';if(prior){state.route=prior.route;state.scenario=prior.scenario;if(prior.legacyPaymentContext)state.legacyPaymentContext=prior.legacyPaymentContext;render(true,prior);}else{state.route='challenges';render(true);}}
function error(message){state.error=message;render();$('#phone-content .error')?.scrollIntoView({block:'nearest'});}
function clearCreation(){state.createConsent=false;state.createReady=false;}
function validTarget(d){if(d.metric==='steps')return /^\d+$/.test(d.target)&&+d.target>=1&&+d.target<=1e9;if(d.metric==='distance')return /^\d+(\.\d{1,6})?$/.test(d.target)&&+d.target>0&&+d.target<=1000;const m=/^(\d+):(\d{1,2})$/.exec(d.target);return m&&+m[2]<60&&+m[1]*60+(+m[2])>0&&+m[1]*60+(+m[2])<=1e9;}
function validateStage(){const d=state.draft;
 if(state.route==='createActivity'){if(d.metric==='timed'&&(!/^\d+(\.\d{1,6})?$/.test(d.distance)||+d.distance<=0||+d.distance>1000))return 'Enter a running distance above 0 and up to 1,000 km.';if(d.kind==='personal'&&!validTarget(d))return d.metric==='steps'?'Enter a whole-number step goal above zero.':d.metric==='distance'?'Enter a distance above 0 and up to 1,000 km.':'Enter a time as minutes:seconds, such as 30:00.';}
 if(state.route==='createDates'&&(!/^\d+$/.test(d.days)||+d.days<1||+d.days>30||d.start<'2026-09-23'||d.start>'2026-10-21'||!/^2026-\d{2}-\d{2}$/.test(d.start)))return 'Choose 1–30 full days and a start from Sep 23 through Oct 21, 2026.';
 if(state.route==='createAmount'&&(!/^\d+$/.test(d.amount)||+d.amount<1||+d.amount>500))return 'Choose a whole-dollar simulated amount from $1 to $500.';
 return null;}
function validateDraft(){
 const d=state.draft;
 if(!['personal','friends','leaderboard'].includes(d.kind)||!['steps','minutes','distance','timed'].includes(d.metric))return 'Choose a challenge type and activity before saving.';
 if(d.metric==='timed'&&(!/^\d+(\.\d{1,6})?$/.test(d.distance)||+d.distance<=0||+d.distance>1000))return 'Enter a running distance above 0 and up to 1,000 km.';
 if(d.kind==='personal'&&!validTarget(d))return 'Enter a valid goal before saving.';
 const date=new Date(d.start+'T12:00:00Z');
 if(!/^\d+$/.test(d.days)||+d.days<1||+d.days>30||!Number.isFinite(date.getTime())||date.toISOString().slice(0,10)!==d.start||d.start<'2026-09-23'||d.start>'2026-10-21')return 'Choose 1–30 full days and a start from Sep 23 through Oct 21, 2026.';
 if(!['America/Los_Angeles','America/New_York','Europe/London','UTC'].includes(d.zone))return 'Choose a time zone before saving.';
 if(!/^\d+$/.test(d.amount)||+d.amount<1||+d.amount>500)return 'Choose a whole-dollar simulated amount from $1 to $500.';
 return null;
}
function act(action){state.error='';const [a,v]=action.split(':');
 if(a==='back')return back();if(a==='close'){state.history=[];state.route='challenges';state.scenario='populated';return render(true);}
 if(a==='metric'){state.metric=v;return render();}if(a==='day'){state.day=+v;return render();}if(a==='filter'){state.filter=v;return render();}
 if(a==='refresh'||a==='legacy-refresh'){if(state.route==='legacyReview'||state.route==='review')state.scenario='pending';else state.scenario='populated';$('#announcement').textContent='Saved demo information refreshed.';return render();}
 if(a==='request'){state.invitation='requested';return go('lobby');}if(a==='decline'){state.invitation='declined';return render();}if(a==='withdraw-request'){state.invitation='open';return go('invitation');}
 if(a==='demo-select')return go('selection');if(a==='select-roster'&&state.selected)return go('proposal');
 if(a==='propose'){if(!/^\d+$/.test(state.goal)||+state.goal<1||+state.goal>1e9)return error('Enter a whole-number step goal above zero.');state.proposed=true;state.consent=false;state.friendReady=false;return go('agreement');}
 if(a==='friend-check'){state.friendReady=true;return render();}if(a==='community-check'){state.communityReady=true;return render();}if(a==='demo-sam-agree'){state.samAgreed=true;return render();}
 if(a==='agree'&&state.consent&&state.friendReady&&!state.friendAgreement){if(capacityBlocked())return;if(!/^\d+$/.test(state.goal)||+state.goal<1||+state.goal>1e9)return error('Enter a whole-number step goal above zero.');state.friendAgreement=Object.freeze({goal:state.goal,savedAt:'Sep 21, 2026 · 10:00 AM Pacific'});state.joined=true;state.invitation='agreed';state.consent=false;return go('confirmation');}
 if(a==='demo-review'){state.scenario='pending';state.resultMode='pending';return render();}if(a==='demo-legacy-review'){state.scenario='pending';return render();}
 if(a==='save-review'){if(!state.reviewReason)return error('Choose what you’d like us to check.');if(['offline','loading','unavailable'].includes(state.scenario))return;state.reviewSaved=true;return go('reviewReceipt');}
 if(a==='exit'&&exitNames[v]){state.exitKind=v;return go('exit');}if(a==='view-exit'&&state.exits[v]){state.viewExitKind=v;return go('exitReceipt');}if(a==='confirm-exit'){state.exits[state.exitKind]??=Object.freeze({name:exitNames[state.exitKind],savedAt:(state.exitKind==='community'&&state.communityPhase==='active'?'Sep 26':'Sep 21')+', 2026 · 10:00 AM Pacific'});state.viewExitKind=state.exitKind;if(state.exitKind==='community'){state.communityJoined=false;state.communityConsent=false;}return go('exitReceipt');}
 if(a==='community-unavailable'){state.scenario='empty';return render();}if(a==='join-community'&&state.communityConsent&&state.communityReady&&!state.exits.community){if(capacityBlocked())return;state.communityJoined=true;return go('communityConfirmation');}
 if(a==='legacy-start'&&state.legacyConsent){state.legacyStarted=true;return render(true);}if(a==='legacy-review-save'&&!['offline','loading','unavailable'].includes(state.scenario)){state.legacyReviewSaved=true;return go('legacyReceipt');}if(a==='legacy-exit-save'){state.legacyLeft=true;state.scenario='populated';return go('legacyExitReceipt');}if(a==='legacy-replay-payment')return go('legacyPayment');
 if(a==='create-personal'){state.draft.kind='personal';state.createDirect=true;clearCreation();return go('createActivity');}
 if(a==='create-kind'){state.draft.kind=v;state.createDirect=false;clearCreation();return render();}if(a==='create-metric'){state.draft.metric=v;state.draft.target='';state.draft.distance='';clearCreation();return render();}if(a==='create-suggest'){state.draft.target=action.substring('create-suggest:'.length);clearCreation();return render();}
 if(a==='create-next'){const invalid=validateStage();if(invalid)return error(invalid);const steps=['createType','createActivity','createDates','createAmount','createReview'];return go(steps[steps.indexOf(state.route)+1]);}
 if(a==='create-check'){if(['loading','unavailable'].includes(state.scenario))return;state.scenario='populated';state.createReady=true;return render();}
 if(a==='create-save'){if(state.created)return error('Your challenge is already saved. Open the saved confirmation to see it.');const invalid=validateDraft();if(invalid)return error(invalid);if(['loading','offline','unavailable'].includes(state.scenario))return error('We couldn’t confirm the current details. Refresh before saving.');if(state.draft.kind==='personal'&&(!state.createConsent||!state.createReady))return error('Check your activity and agree to the complete rules before saving.');if(state.draft.kind==='personal'&&capacityBlocked())return;state.created=structuredClone(state.draft);return go('createSaved');}
 if(a==='create-link'){state.linkMade=true;return render();}
}
$('#screen-picker').innerHTML=Object.entries(routes).map(([id,[title,group]])=>`<option value="${id}">${group} · ${title}</option>`).join('');
$('#compare-screen').innerHTML=$('#screen-picker').innerHTML;
document.addEventListener('click',e=>{const el=e.target.closest('button,[data-go]');if(!el||el.disabled)return;if(el.dataset.go){e.preventDefault();if(el.dataset.go==='createType'){state.createDirect=false;}return go(el.dataset.go,!!el.closest('#journey-nav'));}if(el.dataset.action)act(el.dataset.action);});
document.addEventListener('input',e=>{const el=e.target;if(el.id==='day-selector'){state.day=+el.value;render();return;}if(el.id==='feedback-note'){state.feedback[state.route]=el.value;return;}if(!el.dataset.field)return;const key=el.dataset.field;if(key.startsWith('draft.')){state.draft[key.split('.')[1]]=el.value;clearCreation();}else {if(key==='goal'&&state.friendAgreement)return;state[key]=el.value;if(key==='goal'){state.consent=false;state.friendReady=false;}}});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.check){state[el.dataset.check]=el.checked;render();return;}if(el.dataset.field){if(el.dataset.field.startsWith('draft.')){state.draft[el.dataset.field.split('.')[1]]=el.value;clearCreation();}else state[el.dataset.field]=el.value;if(el.tagName==='SELECT')render();return;}if(el.id==='screen-picker'||el.id==='compare-screen')return go(el.value,true);if(el.id==='scenario'){state.scenario=el.value;if(state.route.startsWith('create'))clearCreation();if(state.route==='result'&&['pending','populated'].includes(el.value))state.resultMode=el.value==='pending'?'pending':'complete';return render(true);}if(el.id==='community-phase'){state.communityPhase=el.value;return render();}if(el.id==='community-privacy'){state.communityDisclosure=el.value;return render();}if(['theme','material','size','text','motion'].includes(el.id)){document.documentElement.dataset[el.id]=el.value;updateComparison();}});
$('#compare').addEventListener('click',()=>{document.body.classList.toggle('compare');$('#compare').setAttribute('aria-pressed',document.body.classList.contains('compare'));updateComparison();});
$('#reset').addEventListener('click',()=>{state=initial();render(true);$('#announcement').textContent='Demo reset. All local choices and agreements cleared.';});
$('#feedback').addEventListener('submit',e=>{e.preventDefault();const text=$('#feedback-note').value.trim();if(!text)return;const payload={screen:state.route,title:routes[state.route][0],scenario:state.scenario,appearance:document.documentElement.dataset.theme,material:document.documentElement.dataset.material,width:document.documentElement.dataset.size,textSize:document.documentElement.dataset.text,feedback:text};if(window.lavish?.queuePrompt){window.lavish.queuePrompt('Revise Signal screen '+payload.title+': '+text,{tag:'signal-screen-feedback',text:payload.title+' · '+text,queueKey:'signal-screen-'+state.route,element:$('#feedback'),data:payload});$('#feedback-status').textContent='Queued for this screen. Choose Send to Agent in Lavish when you’re ready.';}else $('#feedback-status').textContent='Open this artifact in Lavish to queue feedback. Your note is still saved locally in this page.';});
window.SignalDemo={get state(){return structuredClone(state);},routes:Object.keys(routes),go,render,reset(){state=initial();render(true);},setScenario(value){state.scenario=value;if(state.route==='result'&&['pending','populated'].includes(value))state.resultMode=value==='pending'?'pending':'complete';render(true);},setMode(key,value){document.documentElement.dataset[key]=value;const el=$('#'+key);if(el)el.value=value;updateComparison();}};
const requested=location.hash.slice(1);if(routes[requested])state.route=requested;render(true);
})();
